WheretyNetworkManager
const short WheretyNetworkManager.HideObjectMessageType
Referenced by OnClientConnect.
const short WheretyNetworkManager.InteractWithObjectMessageType
Referenced by OnClientConnect.
const short WheretyNetworkManager.MoveObjectMessageType
Referenced by OnClientConnect.
const short WheretyNetworkManager.PlayPickupAnimationMessageType
Referenced by OnClientConnect.
const short WheretyNetworkManager.SelectAndShowAttributesMessageType
Referenced by OnClientConnect.
override void WheretyNetworkManager.OnClientConnect(NetworkConnection connection)
References HideObjectMessageType, ReceiveHideObjectMessage, InteractWithObjectMessageType, ReceiveInteractWithObjectMessage, MoveObjectMessageType, ReceiveMoveObjectMessage, PlayPickupAnimationMessageType, ReceivePlayPickupAnimationMessage, SelectAndShowAttributesMessageType, ReceiveSelectAndShowAttributesMessage.
void WheretyNetworkManager.ReceiveHideObjectMessage(NetworkMessage networkMessage)
References UiManager.I, UiManager.HideObject.
Referenced by OnClientConnect.
void WheretyNetworkManager.ReceiveInteractWithObjectMessage(NetworkMessage networkMessage)
References UiManager.I, UiManager.InteractWithObject.
Referenced by OnClientConnect.
void WheretyNetworkManager.ReceiveMoveObjectMessage(NetworkMessage networkMessage)
References ObjectHiveVr.Instance, ObjectHiveVr.Player, MoveObjectMessage.Position.
Referenced by OnClientConnect.
void WheretyNetworkManager.ReceivePlayPickupAnimationMessage(NetworkMessage networkMessage)
Referenced by OnClientConnect.
void WheretyNetworkManager.ReceiveSelectAndShowAttributesMessage(NetworkMessage networkMessage)
References ObjectHiveVr.Instance, ObjectHiveVr.SelectAndShowAttributes.
Referenced by OnClientConnect.