GeometryCommon
static int [] GeometryCommon.GetIndicesOfSmoothSection(int startIndex, int verticesInSectionCount)
Referenced by CylinderBuilder.Build, RectangularToroidBuilder.Build, ShearedCylinderBuilder.Build, ToroidBuilder.Build, TruncatedShiftedConeBuilder.Build.
static int [] GeometryCommon.GetIndicesOfSmoothDomedSection(int startIndex, int verticesInSectionCount)
Referenced by EllipticalLathingBuilder.Build, SphereBuilder.Build, SphericalLathingBuilder.Build.
static int [] GeometryCommon.TriangulateCapBySectionIndices(int[] sectionVerticesIndices)
Referenced by CylinderBuilder.Build, EllipticalLathingBuilder.Build, RectangularToroidBuilder.Build, ShearedCylinderBuilder.Build, SphereBuilder.Build, SphericalLathingBuilder.Build, ToroidBuilder.Build, TruncatedShiftedConeBuilder.Build.
static List<Vector3> GeometryCommon.CreateVerticesRotatedSection(List< Vector3 > sourceSection, Quaternion rotation)
Referenced by EllipticalLathingBuilder.Build, RectangularToroidBuilder.Build, SphereBuilder.Build, SphericalLathingBuilder.Build, ToroidBuilder.Build.
static int [] GeometryCommon.Triangulate2SectionsByIndices(int[] startSectionVerticesIndices, int[] endSectionVerticesIndices)
Referenced by CylinderBuilder.Build, EllipticalLathingBuilder.Build, RectangularToroidBuilder.Build, ShearedCylinderBuilder.Build, SphereBuilder.Build, SphericalLathingBuilder.Build, ToroidBuilder.Build, TruncatedShiftedConeBuilder.Build.
static Mesh GeometryCommon.CreateMesh(List< Vector3 > vertices, List< int > indices, List< Vector2 > uvs=null)
Referenced by BoxBuilder.Build, CylinderBuilder.Build, EllipticalLathingBuilder.Build, EquidistantSphereBuilder.Build, RectangularToroidBuilder.Build, ShearedCylinderBuilder.Build, SphereBuilder.Build, SphericalLathingBuilder.Build, ToroidBuilder.Build, TruncatedShiftedConeBuilder.Build.
static List<Vector3> GeometryCommon.CreateVerticesForSmoothCircleSection(Vector3 offset, Vector3 startPoint, Vector3 rotationAxis, float circularStep)
Referenced by CylinderBuilder.Build, ShearedCylinderBuilder.Build, ToroidBuilder.Build, TruncatedShiftedConeBuilder.Build.