ModelImportUiVr
RectTransform ModelImportUiVr.ContentRect
Referenced by ReplaceCurrentDisplayableContent, ShowPage.
RectTransform ModelImportUiVr.ControlsRect
GameObject ModelImportUiVr.FileUsagePreferenceItemUiPrefab
Referenced by ReplaceCurrentDisplayableContent, ShowPage.
GameObject ModelImportUiVr.ShowNthPageButtonPrefab
GameObject ModelImportUiVr.PrevPageButtonGo
GameObject ModelImportUiVr.NextPageButtonGo
List<FileUsagePreference> ModelImportUiVr.FileUsagePreferences
Referenced by ReplaceCurrentDisplayableContent, InitializeAllFilesToLoadModels, ShowPage.
float ModelImportUiVr._itemHeight
int ModelImportUiVr._itemsPerPage
int ModelImportUiVr._currentPageIndex
int ModelImportUiVr._pagesCount
int ModelImportUiVr._currentCentralPageButtonIndex
Dictionary<int, GameObject> ModelImportUiVr._showNthPagesButtonsGos
void ModelImportUiVr.ReplaceCurrentDisplayableContent(List< FileUsagePreference > fileUsagePreferences, int pageIndex)
References FileUsagePreferenceItemUiPrefab, ContentRect, FileUsagePreferences.
Referenced by ShowPage.
void ModelImportUiVr.InitializeAllFilesToLoadModels()
References ObjectHiveVr.Instance, ObjectHiveVr.ModelImportManager, ModelImportManager.GetObjFilesList, FileUsagePreferences, ImportModels.
Referenced by VrMpPlayer.Start.
void ModelImportUiVr.ShowPage(int pageIndex)
References ReplaceCurrentDisplayableContent, FileUsagePreferences, ShowNthPageButtonUi.Button, FileUsagePreferenceItemUiPrefab, ContentRect.
Referenced by Show.
void ModelImportUiVr.ImportModels()
References ObjectHiveVr.Instance.
Referenced by InitializeAllFilesToLoadModels.
void ModelImportUiVr.Show(object dataObject)
Parameter needs for interface signature
dataObject useless parameter
References ShowPage.
void ModelImportUiVr.Hide()
void ModelImportUiVr.CenterOnNextPage()
void ModelImportUiVr.CenterOnPrevPage()
void ModelImportUiVr.DestroyShowNthPagesButtons()
void ModelImportUiVr.GeneratePagesControlsButtons(int pageIndex)
void ModelImportUiVr.ClearPage()
IEnumerator ModelImportUiVr.ImportModelsAsync()