ModelImportUi
RectTransform ModelImportUi.ContentRect
Referenced by ReplaceCurrentDisplayableContent, ShowPage.
RectTransform ModelImportUi.ControlsRect
GameObject ModelImportUi.FileUsagePreferenceItemUiPrefab
Referenced by ReplaceCurrentDisplayableContent, ShowPage.
GameObject ModelImportUi.ShowNthPageButtonPrefab
GameObject ModelImportUi.PrevPageButtonGo
GameObject ModelImportUi.NextPageButtonGo
List<FileUsagePreference> ModelImportUi.FileUsagePreferences
Referenced by ReplaceCurrentDisplayableContent, InitializeAllFilesToLoadModels, ShowPage.
float ModelImportUi._itemHeight
int ModelImportUi._itemsPerPage
int ModelImportUi._currentPageIndex
int ModelImportUi._pagesCount
int ModelImportUi._currentCentralPageButtonIndex
Dictionary<int, GameObject> ModelImportUi._showNthPagesButtonsGos
void ModelImportUi.ReplaceCurrentDisplayableContent(List< FileUsagePreference > fileUsagePreferences, int pageIndex)
References FileUsagePreferenceItemUiPrefab, ContentRect, FileUsagePreferences.
Referenced by ShowPage.
void ModelImportUi.InitializeAllFilesToLoadModels()
References ObjectHive.Instance, ObjectHive.ModelImportManager, ModelImportManager.GetObjFilesList, FileUsagePreferences, ImportModels.
Referenced by Player.Start.
void ModelImportUi.ShowPage(int pageIndex)
References ReplaceCurrentDisplayableContent, FileUsagePreferences, ShowNthPageButtonUi.Button, FileUsagePreferenceItemUiPrefab, ContentRect.
Referenced by Show, ShowNthPageButtonUi.OnButtonClick, ShowNthPageButtonUiVr.OnButtonClick.
void ModelImportUi.ImportModels()
References ObjectHive.Instance.
Referenced by InitializeAllFilesToLoadModels.
void ModelImportUi.Show(object dataObject)
Parameter needs for interface signature
dataObject useless parameter
References ShowPage.
void ModelImportUi.Hide()
void ModelImportUi.CenterOnNextPage()
void ModelImportUi.CenterOnPrevPage()
void ModelImportUi.DestroyShowNthPagesButtons()
void ModelImportUi.GeneratePagesControlsButtons(int pageIndex)
void ModelImportUi.ClearPage()
IEnumerator ModelImportUi.ImportModelsAsync()