AttReader
static Dictionary<string, Dictionary<string, string> > AttReader.Read(string fileName)
Referenced by LoadAndAttachAttributes, AttReaderTester.Start.
static void AttReader.AttachAttributesToObjectsInScene(Dictionary< string, Dictionary< string, string >> entities)
References AttData.NameFromAttributes.
Referenced by LoadAndAttachAttributes.
static void AttReader.LoadAndAttachAttributes(string fileName)
References Read, AttachAttributesToObjectsInScene.
Referenced by RvmConverter.Import.
static void AttReader.Highlight()