GraphicsSettingsManager
const string GraphicsSettingsManager.KeyLod
const string GraphicsSettingsManager.KeyScrRelTransH
const string GraphicsSettingsManager.KeyRevStep
const string GraphicsSettingsManager.KeyCircStep
const string GraphicsSettingsManager.KeyLodsCount
const string GraphicsSettingsManager.KeyCaps
void GraphicsSettingsManager.StoreLodSettings(ShapeTypes shapeType, List< LodSettings > lodSettings)
Referenced by GraphicsSettingsManager.
List<LodSettings> GraphicsSettingsManager.ReadLodSettings(ShapeTypes shapeType)
void GraphicsSettingsManager.StoreEdgedLathingLodSettings(ShapeTypes shapeType, List< EdgedLathingLodSettings > lodSettings)
Referenced by GraphicsSettingsManager.
List<LodSettings> GraphicsSettingsManager.ReadEdgedLathingLodSettings(ShapeTypes shapeType)
void GraphicsSettingsManager.StoreSmoothLathingLodSettings(ShapeTypes shapeType, List< SmoothLathingLodSettings > lodSettings)
Referenced by GraphicsSettingsManager.
List<LodSettings> GraphicsSettingsManager.ReadSmoothLathingLodSettings(ShapeTypes shapeType)
GraphicsSettingsManager.GraphicsSettingsManager()
References StoreLodSettings, StoreEdgedLathingLodSettings, StoreSmoothLathingLodSettings.
void GraphicsSettingsManager.StoreLodSettings(int shapeTypeId, int lodIndex, LodSettings lodSettings)
void GraphicsSettingsManager.DeleteLodSettings(int shapeTypeId)
LodSettings GraphicsSettingsManager.ReadLodSettings(int shapeTypeId, int lodIndex)
void GraphicsSettingsManager.StoreEdgedLathingLodSettings(int shapeTypeId, int lodIndex, EdgedLathingLodSettings lodSettings)
void GraphicsSettingsManager.DeleteEdgedLathingLodSettings(int shapeTypeId)
EdgedLathingLodSettings GraphicsSettingsManager.ReadEdgedLathingLodSettings(int shapeTypeId, int lodIndex)
void GraphicsSettingsManager.StoreSmoothLathingLodSettings(int shapeTypeId, int lodIndex, SmoothLathingLodSettings lodSettings)
void GraphicsSettingsManager.DeleteSmoothLathingLodSettings(int shapeTypeId)
SmoothLathingLodSettings GraphicsSettingsManager.ReadSmoothLathingLodSettings(int shapeTypeId, int lodIndex)
string GraphicsSettingsManager.NthLodKey(int shapeTypeId, int lodIndex)
string GraphicsSettingsManager.LodKey(int shapeTypeId)