UiManager
GameObject UiManager.InformationPanel
Referenced by ShowInfoPanel, HideInfoPanel.
ModelImportUi UiManager.ModelImportUi
Referenced by Player.Start.
ActionMenuUi UiManager.ActionMenuUi
ProgressUi UiManager.ProgressUi
GameObject UiManager.ShowModelImportUiButton
Referenced by HideCurrentWindow, UpdateWindow.
UiManager UiManager._instance
IWindow UiManager._currentWindow
UiManager UiManager.I
Referenced by KeyboardInputController.Update, WheretyNetworkManager.ReceiveHideObjectMessage, WheretyNetworkManager.ReceiveInteractWithObjectMessage, Player.Start, HideCurrentWindow, UpdateWindow, ActionMenuUi.Show, ActionMenuUi.Interact, ActionMenuUi.HidePart.
void UiManager.ShowModelImportUi()
Referenced by KeyboardInputController.Update.
void UiManager.ShowActionMenuUi(InteractionObject interactionObject)
void UiManager.ShowProgressUi(ProgressData data)
References UpdateWindow.
void UiManager.HideCurrentWindow()
References IWindow.Hide, ObjectHive.Instance, ObjectHive.PlayerController, ObjectHive.Aim, I, ShowModelImportUiButton.
Referenced by ActionMenuUi.Show, ActionMenuUi.Interact, ActionMenuUi.HidePart.
void UiManager.UpdateWindow(IWindow window, object dataObject=null)
References ObjectHive.Instance, ObjectHive.PlayerController, ObjectHive.Aim, I, ShowModelImportUiButton, IWindow.Show.
Referenced by ShowProgressUi.
void UiManager.HideObject(string objectName)
Referenced by WheretyNetworkManager.ReceiveHideObjectMessage.
void UiManager.InteractWithObject(string objectName)
Referenced by WheretyNetworkManager.ReceiveInteractWithObjectMessage.
void UiManager.ShowInfoPanel(string message)
References InformationPanel.
void UiManager.HideInfoPanel()
References InformationPanel.
void UiManager.ShowWindow(IWindow window, object dataObject=null)