SceneShapesInstantiator
BuilderSettings SceneShapesInstantiator.BuilderSettings
Referenced by CreateAllShapes.
bool SceneShapesInstantiator.OptimizeForStaticBatching
Referenced by CreateAllShapes.
int SceneShapesInstantiator.DuplicatesThresholdForSwitchingToInstancing
Referenced by CreateAllShapes.
bool SceneShapesInstantiator.TruncatedPyramids
Referenced by CreateAllShapes.
bool SceneShapesInstantiator.Boxes
Referenced by CreateAllShapes.
bool SceneShapesInstantiator.RectangularToroids
Referenced by CreateAllShapes.
bool SceneShapesInstantiator.Toroids
Referenced by CreateAllShapes.
bool SceneShapesInstantiator.EllipticalDishes
Referenced by CreateAllShapes.
bool SceneShapesInstantiator.SphericalDishes
Referenced by CreateAllShapes.
bool SceneShapesInstantiator.Snouts
Referenced by CreateAllShapes.
bool SceneShapesInstantiator.Cylinders
Referenced by CreateAllShapes.
bool SceneShapesInstantiator.Spheres
Referenced by CreateAllShapes.
bool SceneShapesInstantiator.CreateMultipleMeshes
Referenced by CreateAllShapes.
bool SceneShapesInstantiator.ShearedCylinders
Referenced by CreateAllShapes.
Transform SceneShapesInstantiator.RootTransform
Referenced by RvmConverter.Import, CreateHierarchy.
Material SceneShapesInstantiator.StandardMaterial
Referenced by CreateAllShapes.
Transform SceneShapesInstantiator.CameraRig
Referenced by SetModelRotationAndMirroring.
Dictionary<PrimitiveShapeData, GameObject> [] SceneShapesInstantiator._prefabs
Vector3 SceneShapesInstantiator._centerOfModel
Transform SceneShapesInstantiator._prefabsStorage
Transform SceneShapesInstantiator._staticObjectsParent
Color [] SceneShapesInstantiator._colors
ShapeDataRepository SceneShapesInstantiator.ShapeDataRepository
void SceneShapesInstantiator.SetShapeDataRepository(ShapeDataRepository dataRepository)
Referenced by RvmConverter.Import.
void SceneShapesInstantiator.CreateHierarchy()
References ShapeDataRepository.Nodes, RootTransform.
Referenced by RvmConverter.Import.
void SceneShapesInstantiator.CreateAllShapes()
References BuilderSettings, ShapeDataRepository.Nodes, ShapeDataRepository.Shapes, TruncatedPyramids, TruncatedPyramidBuilder.Build, RectangularToroids, RectangularToroidBuilder.Build, Toroids, ToroidBuilder.Build, SphericalDishes, SphericalLathingBuilder.Build, Snouts, TruncatedShiftedConeBuilder.Build, ShearedCylinders, ShearedCylinderBuilder.Build, Boxes, BoxBuilder.Build, EllipticalDishes, EllipticalLathingBuilder.Build, Cylinders, CylinderBuilder.Build, Spheres, SphereBuilder.Build, CreateMultipleMeshes, ShapeDataRepository.AllShapesIds, StandardMaterial, MultipleMeshBuilder.Build, OptimizeForStaticBatching, DuplicatesThresholdForSwitchingToInstancing.
Referenced by RvmConverter.Import.
void SceneShapesInstantiator.SetModelRotationAndMirroring()
References ShapeDataRepository.Nodes, CameraRig.
Referenced by RvmConverter.Import.
void SceneShapesInstantiator.CreateAllColliders()
References ShapeDataRepository.Nodes.
void SceneShapesInstantiator.AssignColorsToAllShapes()
References ShapeDataRepository.Shapes, ShapeDataRepository.Nodes.
Referenced by RvmConverter.Import.
void SceneShapesInstantiator.CreateColliders()
References ShapeDataRepository.Nodes, Node.ChildrenIds, AttData.NameFromAttributes, Node.Name.
Referenced by RvmConverter.Import.
void SceneShapesInstantiator.CreateChildren(Transform parent, Node node)
void SceneShapesInstantiator.CreateNodeColliders(Node node)
int SceneShapesInstantiator.IsClone(List< MultipleMeshShapeData > uniqueMeshes, MultipleMeshShapeData currentMeshes)
bool SceneShapesInstantiator.CheckIsMeshNonDuplicateBySubobjectsCount(MeshData[] md0, MeshData[] md1)
bool SceneShapesInstantiator.CheckIsMeshNonDuplicateByVerticesCongruence(MeshData[] md0, MeshData[] md1)
bool SceneShapesInstantiator.CheckIsMeshNonDuplicateBySegmentsLength(MeshData[] md0, MeshData[] md1)
void SceneShapesInstantiator.SetTransformMrMf(Transform target, Matrix4x4 transformMatrix, int parentId, bool worldPositionStays=true)
void SceneShapesInstantiator.BuildParametersMatchableShapes(int shapeTypeId, Func< PrimitiveShapeData, LodSettings, Mesh > buildMethod)
void SceneShapesInstantiator.BuildParametersMatchableShapes2(int shapeTypeId, Func< PrimitiveShapeData, LodSettings, Mesh > buildMethod)
void SceneShapesInstantiator.BuildScalableShapes(int shapeTypeId, PrimitiveShapeData bsd, int[] scalingParametersIndexes, Func< PrimitiveShapeData, LodSettings, Mesh > buildMethod)
GameObject SceneShapesInstantiator.FindPrefabWithSameParameters(PrimitiveShapeData sd, Dictionary< PrimitiveShapeData, GameObject > prefabsDict)
int SceneShapesInstantiator.FindCloneBySameParameters(PrimitiveShapeData currentPsd, List< PrimitiveShapeData > psds)
void SceneShapesInstantiator.AlignWithParentsMultipleMeshDataInStorage()
void SceneShapesInstantiator.InitializeColors()
void SceneShapesInstantiator.SetColorPropertyBlock(MeshRenderer mr, byte colorIndex)
void SceneShapesInstantiator.SetColorToTransformsChildrenRenderers(Transform tr, byte colorIndex)
void SceneShapesInstantiator.CreateSimpleCollider(Transform container)