InteractablePart
Material [] InteractablePart._normalMaterials
void InteractablePart.Highlight()
References ObjectHiveVr.Instance, ObjectHiveVr.HighlightionMaterial.
Referenced by ObjectHiveVr.HighlightObject.
void InteractablePart.Select(string nickname="")
References ObjectHiveVr.Instance, ObjectHiveVr.SelectionMaterial.
void InteractablePart.Unhighlight()
Referenced by ObjectHiveVr.HighlightObject.
void InteractablePart.Deselect()
References UiManagerVr.I, UiManagerVr.HideInfoPad.
Referenced by ObjectHiveVr.DeselectObject.
void InteractablePart.ShowAttributeData(string nickname="")
void InteractablePart.StoreMaterials()
void InteractablePart.SetMaterials(Material material)
void InteractablePart.RestoreMaterials()
void InteractablePart.OnAttachedToHand(Hand hand)
void InteractablePart.OnDetachedFromHand(Hand hand)
List<MeshRenderer> InteractablePart.GetAllChildrensMeshRenderers(Transform tr)