InteractionObject
Valve.VR.InteractionSystem.InteractableHoverEvents InteractionObject._hoverEvents
MeshRenderer InteractionObject._mr
Color InteractionObject._initialColor
void InteractionObject.Start()
Referenced by SetHoverEvents.
void InteractionObject.Highlight()
Referenced by SetHoverEvents.
void InteractionObject.Leave()
Referenced by SetHoverEvents.
virtual void InteractionObject.Select()
void InteractionObject.SetHoverEvents(Valve.VR.InteractionSystem.InteractableHoverEvents ihe)
References Start, Highlight, Leave.