IWindow
void IWindow.Show(object dataObject=null)
Referenced by UiManager.UpdateWindow, UiManagerVr.UpdateWindow.
void IWindow.Hide()
Referenced by UiManager.HideCurrentWindow, UiManagerVr.HideCurrentWindow.