.TH "ActionMenuUi" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionMenuUi
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and \fBIWindow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHide\fP ()"
.br
.ti -1c
.RI "void \fBShow\fP (object interactionObject)"
.br
.RI "Behaviour is driven by necessary object of \fBInteractionObject\fP type "
.ti -1c
.RI "void \fBInteract\fP ()"
.br
.ti -1c
.RI "void \fBHidePart\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBInteractionObject\fP \fBInteractionObject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file ActionMenuUi\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void ActionMenuUi\&.Hide ()"

.PP
Implements \fBIWindow\fP\&.
.PP
Definition at line 9 of file ActionMenuUi\&.cs\&.
.SS "void ActionMenuUi\&.HidePart ()"

.PP
Definition at line 54 of file ActionMenuUi\&.cs\&.
.SS "void ActionMenuUi\&.Interact ()"

.PP
Definition at line 30 of file ActionMenuUi\&.cs\&.
.SS "void ActionMenuUi\&.Show (object interactionObject)"

.PP
Behaviour is driven by necessary object of \fBInteractionObject\fP type 
.PP
\fBParameters:\fP
.RS 4
\fIinteractionObject\fP object of \fBInteractionObject\fP type
.RE
.PP

.PP
Implements \fBIWindow\fP\&.
.PP
Definition at line 18 of file ActionMenuUi\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBInteractionObject\fP ActionMenuUi\&.InteractionObject"

.PP
Definition at line 7 of file ActionMenuUi\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
