.TH "Aim" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Aim
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBLaserTransform\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file Aim\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Aim\&.Start ()"

.PP
Definition at line 15 of file Aim\&.cs\&.
.SS "void Aim\&.Update ()"

.PP
Definition at line 22 of file Aim\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform Aim\&.LaserTransform"

.PP
Definition at line 6 of file Aim\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
