.TH "AttData" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AttData
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBNameFromAttributes\fP"
.br
.ti -1c
.RI "Dictionary< string, string > \fBAttributes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file AttData\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, string> AttData\&.Attributes"

.PP
Definition at line 7 of file AttData\&.cs\&.
.SS "string AttData\&.NameFromAttributes"

.PP
Definition at line 6 of file AttData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
