.TH "AttReaderTester" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AttReaderTester
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBFileName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file AttReaderTester\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void AttReaderTester\&.Start ()"

.PP
Definition at line 11 of file AttReaderTester\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string AttReaderTester\&.FileName"

.PP
Definition at line 9 of file AttReaderTester\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
