.TH "AttReader" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AttReader
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Dictionary< string, Dictionary< string, string > > \fBRead\fP (string fileName)"
.br
.ti -1c
.RI "static void \fBAttachAttributesToObjectsInScene\fP (Dictionary< string, Dictionary< string, string >> entities)"
.br
.ti -1c
.RI "static void \fBLoadAndAttachAttributes\fP (string fileName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file AttReader\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void AttReader\&.AttachAttributesToObjectsInScene (Dictionary< string, Dictionary< string, string >> entities)\fC [static]\fP"

.PP
Definition at line 152 of file AttReader\&.cs\&.
.SS "static void AttReader\&.LoadAndAttachAttributes (string fileName)\fC [static]\fP"

.PP
Definition at line 185 of file AttReader\&.cs\&.
.SS "static Dictionary<string, Dictionary<string, string> > AttReader\&.Read (string fileName)\fC [static]\fP"

.PP
Definition at line 10 of file AttReader\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
