.TH "BoxBuilder" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BoxBuilder
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Mesh \fBBuild\fP (\fBPrimitiveShapeData\fP boxData, \fBLodSettings\fP lodSettings)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file BoxBuilder\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static Mesh BoxBuilder\&.Build (\fBPrimitiveShapeData\fP boxData, \fBLodSettings\fP lodSettings)\fC [static]\fP"

.PP
Definition at line 7 of file BoxBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
