.TH "BuilderSettings" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BuilderSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBuilderSettings\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBLodSettings\fP > [] \fBLods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file BuilderSettings\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BuilderSettings\&.BuilderSettings ()"

.PP
Definition at line 7 of file BuilderSettings\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBLodSettings\fP> [] BuilderSettings\&.Lods"

.PP
Definition at line 5 of file BuilderSettings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
