.TH "CharacterAnimator" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharacterAnimator
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBThreshold\fP"
.br
.ti -1c
.RI "float \fBTimeThreshold\fP = 0\&.1f"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file CharacterAnimator\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void CharacterAnimator\&.Start ()\fC [protected]\fP"

.PP
Definition at line 17 of file CharacterAnimator\&.cs\&.
.SS "void CharacterAnimator\&.Update ()\fC [protected]\fP"

.PP
Definition at line 25 of file CharacterAnimator\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float CharacterAnimator\&.Threshold"

.PP
Definition at line 7 of file CharacterAnimator\&.cs\&.
.SS "float CharacterAnimator\&.TimeThreshold = 0\&.1f"

.PP
Definition at line 8 of file CharacterAnimator\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
