.TH "ColorTableReader" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorTableReader
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Color [] \fBRead\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBColorNamesFile\fP = 'ColorNames\&.txt'"
.br
.ti -1c
.RI "static string \fBColorCodesFile\fP = 'ColorCodes\&.txt'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ColorTableReader\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static Color [] ColorTableReader\&.Read ()\fC [static]\fP"

.PP
Definition at line 11 of file ColorTableReader\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string ColorTableReader\&.ColorCodesFile = 'ColorCodes\&.txt'\fC [static]\fP"

.PP
Definition at line 9 of file ColorTableReader\&.cs\&.
.SS "string ColorTableReader\&.ColorNamesFile = 'ColorNames\&.txt'\fC [static]\fP"

.PP
Definition at line 8 of file ColorTableReader\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
