.TH "ConnectionUi" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConnectionUi
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConnect\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "InputField \fBPortInput\fP"
.br
.ti -1c
.RI "InputField \fBServerIpAddressInput\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file ConnectionUi\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void ConnectionUi\&.Connect ()"

.PP
Definition at line 18 of file ConnectionUi\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "InputField ConnectionUi\&.PortInput"

.PP
Definition at line 9 of file ConnectionUi\&.cs\&.
.SS "InputField ConnectionUi\&.ServerIpAddressInput"

.PP
Definition at line 10 of file ConnectionUi\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
