.TH "D:/Workspace/Unity/RVM_Importer/Assets/Scripts/Geometry/Builders/Test Directory Reference" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Workspace/Unity/RVM_Importer/Assets/Scripts/Geometry/Builders/Test Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBLathingParameters\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestBoxBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestCylinderBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestEllipticalLathingBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestEquidistantSphereBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestRectangularToroidBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestSlopedCylinderBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestSphereBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestSphericalLathingBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestToroidBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestTruncatedPyramidBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBTestTruncatedShiftedConeBuilder\&.cs\fP"
.br
.in -1c
