.TH "D:/Workspace/Unity/RVM_Importer/Assets/Scripts/Settings Directory Reference" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Workspace/Unity/RVM_Importer/Assets/Scripts/Settings Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGraphicsSettingsManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBNumericControlUi\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlantSettings\&.cs\fP"
.br
.ti -1c
.RI "file \fBSettingsManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBSettingsScene\&.cs\fP"
.br
.ti -1c
.RI "file \fBSettingsWindow\&.cs\fP"
.br
.ti -1c
.RI "file \fBToroidsSettingsWindow\&.cs\fP"
.br
.in -1c
