.TH "D:/Workspace/Unity/RVM_Importer/Assets/Scripts/Geometry/DataModels Directory Reference" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Workspace/Unity/RVM_Importer/Assets/Scripts/Geometry/DataModels Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMeshData\&.cs\fP"
.br
.ti -1c
.RI "file \fBMultipleMeshesData\&.cs\fP"
.br
.ti -1c
.RI "file \fBMultipleMeshShapeData\&.cs\fP"
.br
.ti -1c
.RI "file \fBNode\&.cs\fP"
.br
.ti -1c
.RI "file \fBPolygonData\&.cs\fP"
.br
.ti -1c
.RI "file \fBPrimitiveShapeData\&.cs\fP"
.br
.ti -1c
.RI "file \fBShapeBaseData\&.cs\fP"
.br
.ti -1c
.RI "file \fBShapeData\&.cs\fP"
.br
.in -1c
