.TH "D:/Workspace/Unity/RVM_Importer/Assets/Scripts/Geometry/Builders Directory Reference" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Workspace/Unity/RVM_Importer/Assets/Scripts/Geometry/Builders Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBBuildersSettings\fP"
.br
.ti -1c
.RI "directory \fBTest\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBoxBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBCylinderBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBEllipticalLathingBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBEquidistantSphereBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBGeometryCommon\&.cs\fP"
.br
.ti -1c
.RI "file \fBMultipleMeshBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBRectangularToroidBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBShearedCylinderBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBSphereBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBSphericalLathingBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBToroidBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBTruncatedPyramidBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBTruncatedShiftedConeBuilder\&.cs\fP"
.br
.in -1c
