.TH "D:/Workspace/Unity/RVM_Importer/Assets/Scripts/Geometry/Builders/BuildersSettings Directory Reference" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Workspace/Unity/RVM_Importer/Assets/Scripts/Geometry/Builders/BuildersSettings Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBuilderSettings\&.cs\fP"
.br
.ti -1c
.RI "file \fBEdgedLathingLodSettings\&.cs\fP"
.br
.ti -1c
.RI "file \fBLodSettings\&.cs\fP"
.br
.ti -1c
.RI "file \fBSmoothLathingLodSettings\&.cs\fP"
.br
.in -1c
