.TH "DdsRuntimeLoader" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DdsRuntimeLoader
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Texture2D \fBLoadDdsTexture\fP (string filePath)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file DdsRuntimeLoader\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static Texture2D DdsRuntimeLoader\&.LoadDdsTexture (string filePath)\fC [static]\fP"

.PP
Definition at line 7 of file DdsRuntimeLoader\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
