.TH "DecisionMaker" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DecisionMaker
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SteamVR_Action_Vector2 \fBDecisionSelection\fP"
.br
.ti -1c
.RI "SteamVR_Action_Boolean \fBDecisionCommit\fP"
.br
.ti -1c
.RI "Image [] \fBButtons\fP"
.br
.ti -1c
.RI "Sprite [] \fBNormal\fP"
.br
.ti -1c
.RI "Sprite [] \fBHover\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file DecisionMaker\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Image [] DecisionMaker\&.Buttons"

.PP
Definition at line 12 of file DecisionMaker\&.cs\&.
.SS "SteamVR_Action_Boolean DecisionMaker\&.DecisionCommit"

.PP
Definition at line 10 of file DecisionMaker\&.cs\&.
.SS "SteamVR_Action_Vector2 DecisionMaker\&.DecisionSelection"

.PP
Definition at line 9 of file DecisionMaker\&.cs\&.
.SS "Sprite [] DecisionMaker\&.Hover"

.PP
Definition at line 14 of file DecisionMaker\&.cs\&.
.SS "Sprite [] DecisionMaker\&.Normal"

.PP
Definition at line 13 of file DecisionMaker\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
