.TH "EdgedLathingLodSettings" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EdgedLathingLodSettings
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLodSettings\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEdgedLathingLodSettings\fP (float screenRelativeTransitionHeight, float revoluteStep, bool caps=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly float \fBRevoluteStep\fP"
.br
.ti -1c
.RI "readonly bool \fBCaps\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file EdgedLathingLodSettings\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EdgedLathingLodSettings\&.EdgedLathingLodSettings (float screenRelativeTransitionHeight, float revoluteStep, bool caps = \fCfalse\fP)"

.PP
Definition at line 6 of file EdgedLathingLodSettings\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly bool EdgedLathingLodSettings\&.Caps"

.PP
Definition at line 4 of file EdgedLathingLodSettings\&.cs\&.
.SS "readonly float EdgedLathingLodSettings\&.RevoluteStep"

.PP
Definition at line 3 of file EdgedLathingLodSettings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
