.TH "EquidistantSphereBuilder" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EquidistantSphereBuilder
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Mesh \fBBuild\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file EquidistantSphereBuilder\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static Mesh EquidistantSphereBuilder\&.Build ()\fC [static]\fP"

.PP
Definition at line 6 of file EquidistantSphereBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
