.TH "FileUsagePreferenceItemUi" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileUsagePreferenceItemUi
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetFileUsagePreference\fP (\fBFileUsagePreference\fP value, int index)"
.br
.ti -1c
.RI "void \fBOnIsNeededToggle\fP (bool value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBTitleText\fP"
.br
.ti -1c
.RI "Text \fBIsLoadedText\fP"
.br
.ti -1c
.RI "Toggle \fBIsNeededTogle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file FileUsagePreferenceItemUi\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void FileUsagePreferenceItemUi\&.OnIsNeededToggle (bool value)"

.PP
Definition at line 26 of file FileUsagePreferenceItemUi\&.cs\&.
.SS "void FileUsagePreferenceItemUi\&.SetFileUsagePreference (\fBFileUsagePreference\fP value, int index)"

.PP
Definition at line 16 of file FileUsagePreferenceItemUi\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Text FileUsagePreferenceItemUi\&.IsLoadedText"

.PP
Definition at line 10 of file FileUsagePreferenceItemUi\&.cs\&.
.SS "Toggle FileUsagePreferenceItemUi\&.IsNeededTogle"

.PP
Definition at line 11 of file FileUsagePreferenceItemUi\&.cs\&.
.SS "Text FileUsagePreferenceItemUi\&.TitleText"

.PP
Definition at line 9 of file FileUsagePreferenceItemUi\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
