.TH "FileUsagePreference" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileUsagePreference
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBFileFullAddress\fP"
.br
.ti -1c
.RI "bool \fBIsInspected\fP"
.br
.ti -1c
.RI "bool \fBIsNeeded\fP"
.br
.ti -1c
.RI "bool \fBIsLoaded\fP"
.br
.ti -1c
.RI "GameObject \fBGameObject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2 of file FileUsagePreference\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string FileUsagePreference\&.FileFullAddress"

.PP
Definition at line 4 of file FileUsagePreference\&.cs\&.
.SS "GameObject FileUsagePreference\&.GameObject"

.PP
Definition at line 8 of file FileUsagePreference\&.cs\&.
.SS "bool FileUsagePreference\&.IsInspected"

.PP
Definition at line 5 of file FileUsagePreference\&.cs\&.
.SS "bool FileUsagePreference\&.IsLoaded"

.PP
Definition at line 7 of file FileUsagePreference\&.cs\&.
.SS "bool FileUsagePreference\&.IsNeeded"

.PP
Definition at line 6 of file FileUsagePreference\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
