.TH "GraphicsSettingsManager" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsSettingsManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStoreLodSettings\fP (\fBShapeTypes\fP shapeType, List< \fBLodSettings\fP > lodSettings)"
.br
.ti -1c
.RI "List< \fBLodSettings\fP > \fBReadLodSettings\fP (\fBShapeTypes\fP shapeType)"
.br
.ti -1c
.RI "void \fBStoreEdgedLathingLodSettings\fP (\fBShapeTypes\fP shapeType, List< \fBEdgedLathingLodSettings\fP > lodSettings)"
.br
.ti -1c
.RI "List< \fBLodSettings\fP > \fBReadEdgedLathingLodSettings\fP (\fBShapeTypes\fP shapeType)"
.br
.ti -1c
.RI "void \fBStoreSmoothLathingLodSettings\fP (\fBShapeTypes\fP shapeType, List< \fBSmoothLathingLodSettings\fP > lodSettings)"
.br
.ti -1c
.RI "List< \fBLodSettings\fP > \fBReadSmoothLathingLodSettings\fP (\fBShapeTypes\fP shapeType)"
.br
.ti -1c
.RI "\fBGraphicsSettingsManager\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file GraphicsSettingsManager\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GraphicsSettingsManager\&.GraphicsSettingsManager ()"

.PP
Definition at line 210 of file GraphicsSettingsManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "List<\fBLodSettings\fP> GraphicsSettingsManager\&.ReadEdgedLathingLodSettings (\fBShapeTypes\fP shapeType)"

.PP
Definition at line 113 of file GraphicsSettingsManager\&.cs\&.
.SS "List<\fBLodSettings\fP> GraphicsSettingsManager\&.ReadLodSettings (\fBShapeTypes\fP shapeType)"

.PP
Definition at line 52 of file GraphicsSettingsManager\&.cs\&.
.SS "List<\fBLodSettings\fP> GraphicsSettingsManager\&.ReadSmoothLathingLodSettings (\fBShapeTypes\fP shapeType)"

.PP
Definition at line 176 of file GraphicsSettingsManager\&.cs\&.
.SS "void GraphicsSettingsManager\&.StoreEdgedLathingLodSettings (\fBShapeTypes\fP shapeType, List< \fBEdgedLathingLodSettings\fP > lodSettings)"

.PP
Definition at line 73 of file GraphicsSettingsManager\&.cs\&.
.SS "void GraphicsSettingsManager\&.StoreLodSettings (\fBShapeTypes\fP shapeType, List< \fBLodSettings\fP > lodSettings)"

.PP
Definition at line 16 of file GraphicsSettingsManager\&.cs\&.
.SS "void GraphicsSettingsManager\&.StoreSmoothLathingLodSettings (\fBShapeTypes\fP shapeType, List< \fBSmoothLathingLodSettings\fP > lodSettings)"

.PP
Definition at line 136 of file GraphicsSettingsManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
