.TH "D:/Workspace/Unity/RVM_Importer/Assets/Scripts/Temp/InputFiles.cs" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Workspace/Unity/RVM_Importer/Assets/Scripts/Temp/InputFiles.cs
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBInputFiles\fP { \fBInputFiles\&.Small\fP, \fBInputFiles\&.Medium\fP, \fBInputFiles\&.Big\fP, \fBInputFiles\&.Other\fP, \fBInputFiles\&.V_E_4102_07_EK\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBInputFiles\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISmall \fP\fP
.TP
\fB\fIMedium \fP\fP
.TP
\fB\fIBig \fP\fP
.TP
\fB\fIOther \fP\fP
.TP
\fB\fIV_E_4102_07_EK \fP\fP
.PP
Definition at line 1 of file InputFiles\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
