.TH "InteractionObject" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InteractionObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBHighlight\fP ()"
.br
.ti -1c
.RI "void \fBLeave\fP ()"
.br
.ti -1c
.RI "virtual void \fBSelect\fP ()"
.br
.ti -1c
.RI "void \fBSetHoverEvents\fP (Valve\&.VR\&.InteractionSystem\&.InteractableHoverEvents ihe)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file InteractionObject\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void InteractionObject\&.Highlight ()"

.PP
Definition at line 18 of file InteractionObject\&.cs\&.
.SS "void InteractionObject\&.Leave ()"

.PP
Definition at line 23 of file InteractionObject\&.cs\&.
.SS "virtual void InteractionObject\&.Select ()\fC [virtual]\fP"

.PP
Definition at line 28 of file InteractionObject\&.cs\&.
.SS "void InteractionObject\&.SetHoverEvents (Valve\&.VR\&.InteractionSystem\&.InteractableHoverEvents ihe)"

.PP
Definition at line 33 of file InteractionObject\&.cs\&.
.SS "void InteractionObject\&.Start ()"

.PP
Definition at line 12 of file InteractionObject\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
