.TH "InteractablePart" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InteractablePart
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHighlight\fP ()"
.br
.ti -1c
.RI "void \fBSelect\fP (string nickname='')"
.br
.ti -1c
.RI "void \fBUnhighlight\fP ()"
.br
.ti -1c
.RI "void \fBDeselect\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file InteractablePart\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void InteractablePart\&.Deselect ()"

.PP
Definition at line 30 of file InteractablePart\&.cs\&.
.SS "void InteractablePart\&.Highlight ()"

.PP
Definition at line 10 of file InteractablePart\&.cs\&.
.SS "void InteractablePart\&.Select (string nickname = \fC''\fP)"

.PP
Definition at line 17 of file InteractablePart\&.cs\&.
.SS "void InteractablePart\&.Unhighlight ()"

.PP
Definition at line 25 of file InteractablePart\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
