.TH "IWheretyPlayer" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IWheretyPlayer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPlayer\fP, \fBVrMpPlayer\fP, and \fBWheretyPlayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHideObject\fP (string objectName)"
.br
.ti -1c
.RI "void \fBInteractWithObject\fP (string objectName)"
.br
.ti -1c
.RI "void \fBMoveObject\fP (Transform transform)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file IWheretyPlayer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void IWheretyPlayer\&.HideObject (string objectName)"

.PP
Implemented in \fBWheretyPlayer\fP, \fBPlayer\fP, and \fBVrMpPlayer\fP\&.
.SS "void IWheretyPlayer\&.InteractWithObject (string objectName)"

.PP
Implemented in \fBWheretyPlayer\fP, \fBPlayer\fP, and \fBVrMpPlayer\fP\&.
.SS "void IWheretyPlayer\&.MoveObject (Transform transform)"

.PP
Implemented in \fBWheretyPlayer\fP, \fBPlayer\fP, and \fBVrMpPlayer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
