.TH "IWindow" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBActionMenuUi\fP, \fBModelImportUi\fP, \fBModelImportUiVr\fP, and \fBProgressUi\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShow\fP (object dataObject=null)"
.br
.ti -1c
.RI "void \fBHide\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file IWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void IWindow\&.Hide ()"

.PP
Implemented in \fBModelImportUi\fP, \fBModelImportUiVr\fP, \fBProgressUi\fP, and \fBActionMenuUi\fP\&.
.SS "void IWindow\&.Show (object dataObject = \fCnull\fP)"

.PP
Implemented in \fBModelImportUi\fP, \fBModelImportUiVr\fP, \fBProgressUi\fP, and \fBActionMenuUi\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
