.TH "KeyboardButton" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyboardButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddCharToName\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "InputField \fBNameInput\fP"
.br
.ti -1c
.RI "string \fBChar\fP = 'Й'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file KeyboardButton\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void KeyboardButton\&.AddCharToName ()"

.PP
Definition at line 9 of file KeyboardButton\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string KeyboardButton\&.Char = 'Й'"

.PP
Definition at line 7 of file KeyboardButton\&.cs\&.
.SS "InputField KeyboardButton\&.NameInput"

.PP
Definition at line 6 of file KeyboardButton\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
