.TH "LathingParameters" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LathingParameters
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLathingParameters\fP (ref float revoluteStep, ref float fillAngle)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly bool \fBClosed\fP"
.br
.ti -1c
.RI "List< int > \fBIndices\fP"
.br
.ti -1c
.RI "readonly Quaternion \fBRotation\fP"
.br
.ti -1c
.RI "readonly int \fBStepsCount\fP"
.br
.ti -1c
.RI "List< Vector3 > \fBVertices\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file LathingParameters\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LathingParameters\&.LathingParameters (ref float revoluteStep, ref float fillAngle)"

.PP
Definition at line 12 of file LathingParameters\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly bool LathingParameters\&.Closed"

.PP
Definition at line 6 of file LathingParameters\&.cs\&.
.SS "List<int> LathingParameters\&.Indices"

.PP
Definition at line 7 of file LathingParameters\&.cs\&.
.SS "readonly Quaternion LathingParameters\&.Rotation"

.PP
Definition at line 8 of file LathingParameters\&.cs\&.
.SS "readonly int LathingParameters\&.StepsCount"

.PP
Definition at line 9 of file LathingParameters\&.cs\&.
.SS "List<Vector3> LathingParameters\&.Vertices"

.PP
Definition at line 10 of file LathingParameters\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
