.TH "LodSettings" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LodSettings
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBEdgedLathingLodSettings\fP, and \fBSmoothLathingLodSettings\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLodSettings\fP (float screenRelativeTransitionHeight)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly float \fBScreenRelativeTransitionHeight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file LodSettings\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LodSettings\&.LodSettings (float screenRelativeTransitionHeight)"

.PP
Definition at line 5 of file LodSettings\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly float LodSettings\&.ScreenRelativeTransitionHeight"

.PP
Definition at line 3 of file LodSettings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
