.TH "MeshData" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeshData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMeshData\fP (\fBPolygonData\fP[] polygons)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBPolygonData\fP [] \fBPolygons\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file MeshData\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MeshData\&.MeshData (\fBPolygonData\fP [] polygons)"

.PP
Definition at line 5 of file MeshData\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPolygonData\fP [] MeshData\&.Polygons"

.PP
Definition at line 3 of file MeshData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
