.TH "ModelImportUi" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelImportUi
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and \fBIWindow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReplaceCurrentDisplayableContent\fP (List< \fBFileUsagePreference\fP > fileUsagePreferences, int pageIndex)"
.br
.ti -1c
.RI "void \fBInitializeAllFilesToLoadModels\fP ()"
.br
.ti -1c
.RI "void \fBShowPage\fP (int pageIndex)"
.br
.ti -1c
.RI "void \fBImportModels\fP ()"
.br
.ti -1c
.RI "void \fBShow\fP (object dataObject)"
.br
.RI "Parameter needs for interface signature "
.ti -1c
.RI "void \fBHide\fP ()"
.br
.ti -1c
.RI "void \fBCenterOnNextPage\fP ()"
.br
.ti -1c
.RI "void \fBCenterOnPrevPage\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RectTransform \fBContentRect\fP"
.br
.ti -1c
.RI "RectTransform \fBControlsRect\fP"
.br
.ti -1c
.RI "GameObject \fBFileUsagePreferenceItemUiPrefab\fP"
.br
.ti -1c
.RI "GameObject \fBShowNthPageButtonPrefab\fP"
.br
.ti -1c
.RI "GameObject \fBPrevPageButtonGo\fP"
.br
.ti -1c
.RI "GameObject \fBNextPageButtonGo\fP"
.br
.ti -1c
.RI "List< \fBFileUsagePreference\fP > \fBFileUsagePreferences\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file ModelImportUi\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void ModelImportUi\&.CenterOnNextPage ()"

.PP
Definition at line 288 of file ModelImportUi\&.cs\&.
.SS "void ModelImportUi\&.CenterOnPrevPage ()"

.PP
Definition at line 296 of file ModelImportUi\&.cs\&.
.SS "void ModelImportUi\&.Hide ()"

.PP
Implements \fBIWindow\fP\&.
.PP
Definition at line 283 of file ModelImportUi\&.cs\&.
.SS "void ModelImportUi\&.ImportModels ()"

.PP
Definition at line 224 of file ModelImportUi\&.cs\&.
.SS "void ModelImportUi\&.InitializeAllFilesToLoadModels ()"

.PP
Definition at line 171 of file ModelImportUi\&.cs\&.
.SS "void ModelImportUi\&.ReplaceCurrentDisplayableContent (List< \fBFileUsagePreference\fP > fileUsagePreferences, int pageIndex)"

.PP
Definition at line 28 of file ModelImportUi\&.cs\&.
.SS "void ModelImportUi\&.Show (object dataObject)"

.PP
Parameter needs for interface signature 
.PP
\fBParameters:\fP
.RS 4
\fIdataObject\fP useless parameter
.RE
.PP

.PP
Implements \fBIWindow\fP\&.
.PP
Definition at line 277 of file ModelImportUi\&.cs\&.
.SS "void ModelImportUi\&.ShowPage (int pageIndex)"

.PP
Definition at line 178 of file ModelImportUi\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "RectTransform ModelImportUi\&.ContentRect"

.PP
Definition at line 9 of file ModelImportUi\&.cs\&.
.SS "RectTransform ModelImportUi\&.ControlsRect"

.PP
Definition at line 10 of file ModelImportUi\&.cs\&.
.SS "GameObject ModelImportUi\&.FileUsagePreferenceItemUiPrefab"

.PP
Definition at line 12 of file ModelImportUi\&.cs\&.
.SS "List<\fBFileUsagePreference\fP> ModelImportUi\&.FileUsagePreferences"

.PP
Definition at line 18 of file ModelImportUi\&.cs\&.
.SS "GameObject ModelImportUi\&.NextPageButtonGo"

.PP
Definition at line 16 of file ModelImportUi\&.cs\&.
.SS "GameObject ModelImportUi\&.PrevPageButtonGo"

.PP
Definition at line 15 of file ModelImportUi\&.cs\&.
.SS "GameObject ModelImportUi\&.ShowNthPageButtonPrefab"

.PP
Definition at line 13 of file ModelImportUi\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
