.TH "ModelImportManager" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelImportManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "List< \fBFileUsagePreference\fP > \fBGetObjFilesList\fP ()"
.br
.ti -1c
.RI "GameObject \fBImport\fP (\fBFileUsagePreference\fP fileUsagePreference)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRvmConverter\fP \fBRvmConverter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ModelImportManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "List<\fBFileUsagePreference\fP> ModelImportManager\&.GetObjFilesList ()"

.PP
Definition at line 10 of file ModelImportManager\&.cs\&.
.SS "GameObject ModelImportManager\&.Import (\fBFileUsagePreference\fP fileUsagePreference)"

.PP
Definition at line 22 of file ModelImportManager\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRvmConverter\fP ModelImportManager\&.RvmConverter"

.PP
Definition at line 8 of file ModelImportManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
