.TH "MoveObjectMessage" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MoveObjectMessage
.SH SYNOPSIS
.br
.PP
.PP
Inherits MessageBase\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint \fBPlayerNetId\fP"
.br
.ti -1c
.RI "string \fBName\fP"
.br
.ti -1c
.RI "Vector3 \fBPosition\fP"
.br
.ti -1c
.RI "Quaternion \fBRotation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file MoveObjectMessage\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string MoveObjectMessage\&.Name"

.PP
Definition at line 9 of file MoveObjectMessage\&.cs\&.
.SS "uint MoveObjectMessage\&.PlayerNetId"

.PP
Definition at line 8 of file MoveObjectMessage\&.cs\&.
.SS "Vector3 MoveObjectMessage\&.Position"

.PP
Definition at line 10 of file MoveObjectMessage\&.cs\&.
.SS "Quaternion MoveObjectMessage\&.Rotation"

.PP
Definition at line 11 of file MoveObjectMessage\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
