.TH "MultipleMeshesData" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MultipleMeshesData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultipleMeshesData\fP (\fBMeshData\fP[] meshes)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBMeshData\fP [] \fBMeshes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file MultipleMeshesData\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MultipleMeshesData\&.MultipleMeshesData (\fBMeshData\fP [] meshes)"

.PP
Definition at line 7 of file MultipleMeshesData\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBMeshData\fP [] MultipleMeshesData\&.Meshes"

.PP
Definition at line 5 of file MultipleMeshesData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
