.TH "MultipleMeshShapeData" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MultipleMeshShapeData
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShapeData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultipleMeshShapeData\fP (Matrix4x4 transformMatrix, Vector3 boundMin, Vector3 boundMax, int parentId, \fBMultipleMeshesData\fP multipleMeshesData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBMultipleMeshesData\fP \fBMultipleMeshesData\fP"
.br
.ti -1c
.RI "Vector3 \fBOffset\fP"
.br
.ti -1c
.RI "Quaternion \fBRotation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file MultipleMeshShapeData\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MultipleMeshShapeData\&.MultipleMeshShapeData (Matrix4x4 transformMatrix, Vector3 boundMin, Vector3 boundMax, int parentId, \fBMultipleMeshesData\fP multipleMeshesData)"

.PP
Definition at line 10 of file MultipleMeshShapeData\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBMultipleMeshesData\fP MultipleMeshShapeData\&.MultipleMeshesData"

.PP
Definition at line 5 of file MultipleMeshShapeData\&.cs\&.
.SS "Vector3 MultipleMeshShapeData\&.Offset"

.PP
Definition at line 6 of file MultipleMeshShapeData\&.cs\&.
.SS "Quaternion MultipleMeshShapeData\&.Rotation"

.PP
Definition at line 7 of file MultipleMeshShapeData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
