.TH "MultipleMeshBuilder" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MultipleMeshBuilder
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Transform \fBBuildGo\fP (\fBMultipleMeshShapeData\fP shapeData, Transform baseTransform, Material material)"
.br
.ti -1c
.RI "static Mesh \fBBuild\fP (\fBMultipleMeshShapeData\fP shapeData)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file MultipleMeshBuilder\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static Mesh MultipleMeshBuilder\&.Build (\fBMultipleMeshShapeData\fP shapeData)\fC [static]\fP"

.PP
Definition at line 48 of file MultipleMeshBuilder\&.cs\&.
.SS "static Transform MultipleMeshBuilder\&.BuildGo (\fBMultipleMeshShapeData\fP shapeData, Transform baseTransform, Material material)\fC [static]\fP"

.PP
Definition at line 8 of file MultipleMeshBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
