.TH "NumericControlUi" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumericControlUi
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBValue\fP ()"
.br
.ti -1c
.RI "void \fBInc1\fP ()"
.br
.ti -1c
.RI "void \fBInc2\fP ()"
.br
.ti -1c
.RI "void \fBInc3\fP ()"
.br
.ti -1c
.RI "void \fBDec1\fP ()"
.br
.ti -1c
.RI "void \fBDec2\fP ()"
.br
.ti -1c
.RI "void \fBDec3\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBDefaultValue\fP"
.br
.ti -1c
.RI "float \fBMinValue\fP"
.br
.ti -1c
.RI "float \fBMaxValue\fP"
.br
.ti -1c
.RI "float \fBIncrement1\fP = 1f"
.br
.ti -1c
.RI "float \fBIncrement2\fP = 4f"
.br
.ti -1c
.RI "float \fBIncrement3\fP = 16f"
.br
.ti -1c
.RI "float \fBDecrement1\fP = \-1f"
.br
.ti -1c
.RI "float \fBDecrement2\fP = \-4f"
.br
.ti -1c
.RI "float \fBDecrement3\fP = \-16f"
.br
.ti -1c
.RI "int \fBDecimalAccuracy\fP = 0"
.br
.ti -1c
.RI "string \fBHintString\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBValueText\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBIncrement1ButtonText\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBIncrement2ButtonText\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBIncrement3ButtonText\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBDecrement1ButtonText\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBDecrement2ButtonText\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBDecrement3ButtonText\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBHintText\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file NumericControlUi\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NumericControlUi\&.Dec1 ()"

.PP
Definition at line 72 of file NumericControlUi\&.cs\&.
.SS "void NumericControlUi\&.Dec2 ()"

.PP
Definition at line 73 of file NumericControlUi\&.cs\&.
.SS "void NumericControlUi\&.Dec3 ()"

.PP
Definition at line 74 of file NumericControlUi\&.cs\&.
.SS "void NumericControlUi\&.Inc1 ()"

.PP
Definition at line 69 of file NumericControlUi\&.cs\&.
.SS "void NumericControlUi\&.Inc2 ()"

.PP
Definition at line 70 of file NumericControlUi\&.cs\&.
.SS "void NumericControlUi\&.Inc3 ()"

.PP
Definition at line 71 of file NumericControlUi\&.cs\&.
.SS "float NumericControlUi\&.Value ()"

.PP
Definition at line 47 of file NumericControlUi\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int NumericControlUi\&.DecimalAccuracy = 0"

.PP
Definition at line 23 of file NumericControlUi\&.cs\&.
.SS "float NumericControlUi\&.Decrement1 = \-1f"

.PP
Definition at line 19 of file NumericControlUi\&.cs\&.
.SS "TextMeshProUGUI NumericControlUi\&.Decrement1ButtonText"

.PP
Definition at line 33 of file NumericControlUi\&.cs\&.
.SS "float NumericControlUi\&.Decrement2 = \-4f"

.PP
Definition at line 20 of file NumericControlUi\&.cs\&.
.SS "TextMeshProUGUI NumericControlUi\&.Decrement2ButtonText"

.PP
Definition at line 34 of file NumericControlUi\&.cs\&.
.SS "float NumericControlUi\&.Decrement3 = \-16f"

.PP
Definition at line 21 of file NumericControlUi\&.cs\&.
.SS "TextMeshProUGUI NumericControlUi\&.Decrement3ButtonText"

.PP
Definition at line 35 of file NumericControlUi\&.cs\&.
.SS "float NumericControlUi\&.DefaultValue"

.PP
Definition at line 10 of file NumericControlUi\&.cs\&.
.SS "string NumericControlUi\&.HintString"

.PP
Definition at line 25 of file NumericControlUi\&.cs\&.
.SS "TextMeshProUGUI NumericControlUi\&.HintText"

.PP
Definition at line 37 of file NumericControlUi\&.cs\&.
.SS "float NumericControlUi\&.Increment1 = 1f"

.PP
Definition at line 15 of file NumericControlUi\&.cs\&.
.SS "TextMeshProUGUI NumericControlUi\&.Increment1ButtonText"

.PP
Definition at line 29 of file NumericControlUi\&.cs\&.
.SS "float NumericControlUi\&.Increment2 = 4f"

.PP
Definition at line 16 of file NumericControlUi\&.cs\&.
.SS "TextMeshProUGUI NumericControlUi\&.Increment2ButtonText"

.PP
Definition at line 30 of file NumericControlUi\&.cs\&.
.SS "float NumericControlUi\&.Increment3 = 16f"

.PP
Definition at line 17 of file NumericControlUi\&.cs\&.
.SS "TextMeshProUGUI NumericControlUi\&.Increment3ButtonText"

.PP
Definition at line 31 of file NumericControlUi\&.cs\&.
.SS "float NumericControlUi\&.MaxValue"

.PP
Definition at line 13 of file NumericControlUi\&.cs\&.
.SS "float NumericControlUi\&.MinValue"

.PP
Definition at line 12 of file NumericControlUi\&.cs\&.
.SS "TextMeshProUGUI NumericControlUi\&.ValueText"

.PP
Definition at line 27 of file NumericControlUi\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
