.TH "ObjectHiveVr" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectHiveVr
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBHighlightObject\fP (\fBInteractablePart\fP ip)"
.br
.ti -1c
.RI "void \fBSelectAndShowAttributes\fP (string objectName, string nickname='')"
.br
.ti -1c
.RI "void \fBSelectParent\fP ()"
.br
.ti -1c
.RI "void \fBDeselectObject\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBModelImportManager\fP \fBModelImportManager\fP"
.br
.ti -1c
.RI "Valve\&.VR\&.InteractionSystem\&.Teleport \fBTeleport\fP"
.br
.ti -1c
.RI "\fBIWheretyPlayer\fP \fBPlayer\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBNotificationText\fP"
.br
.ti -1c
.RI "Material \fBHighlightionMaterial\fP"
.br
.ti -1c
.RI "Material \fBSelectionMaterial\fP"
.br
.ti -1c
.RI "Transform \fBLocalPlayerHeadTr\fP"
.br
.ti -1c
.RI "Transform \fBLocalPlayerTr\fP"
.br
.ti -1c
.RI "\fBInteractablePart\fP \fBHighlightedInteractionObject\fP"
.br
.ti -1c
.RI "\fBInteractablePart\fP \fBSelectedInteractionObject\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBObjectHiveVr\fP \fBInstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ObjectHiveVr\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void ObjectHiveVr\&.Awake ()"

.PP
Definition at line 33 of file ObjectHiveVr\&.cs\&.
.SS "void ObjectHiveVr\&.DeselectObject ()"

.PP
Definition at line 102 of file ObjectHiveVr\&.cs\&.
.SS "void ObjectHiveVr\&.HighlightObject (\fBInteractablePart\fP ip)"

.PP
Definition at line 38 of file ObjectHiveVr\&.cs\&.
.SS "void ObjectHiveVr\&.SelectAndShowAttributes (string objectName, string nickname = \fC''\fP)"

.PP
Definition at line 51 of file ObjectHiveVr\&.cs\&.
.SS "void ObjectHiveVr\&.SelectParent ()"

.PP
Definition at line 86 of file ObjectHiveVr\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBInteractablePart\fP ObjectHiveVr\&.HighlightedInteractionObject"

.PP
Definition at line 18 of file ObjectHiveVr\&.cs\&.
.SS "Material ObjectHiveVr\&.HighlightionMaterial"

.PP
Definition at line 12 of file ObjectHiveVr\&.cs\&.
.SS "Transform ObjectHiveVr\&.LocalPlayerHeadTr"

.PP
Definition at line 15 of file ObjectHiveVr\&.cs\&.
.SS "Transform ObjectHiveVr\&.LocalPlayerTr"

.PP
Definition at line 16 of file ObjectHiveVr\&.cs\&.
.SS "\fBModelImportManager\fP ObjectHiveVr\&.ModelImportManager"

.PP
Definition at line 8 of file ObjectHiveVr\&.cs\&.
.SS "TextMeshProUGUI ObjectHiveVr\&.NotificationText"

.PP
Definition at line 11 of file ObjectHiveVr\&.cs\&.
.SS "\fBIWheretyPlayer\fP ObjectHiveVr\&.Player"

.PP
Definition at line 10 of file ObjectHiveVr\&.cs\&.
.SS "\fBInteractablePart\fP ObjectHiveVr\&.SelectedInteractionObject"

.PP
Definition at line 19 of file ObjectHiveVr\&.cs\&.
.SS "Material ObjectHiveVr\&.SelectionMaterial"

.PP
Definition at line 13 of file ObjectHiveVr\&.cs\&.
.SS "Valve\&.VR\&.InteractionSystem\&.Teleport ObjectHiveVr\&.Teleport"

.PP
Definition at line 9 of file ObjectHiveVr\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBObjectHiveVr\fP ObjectHiveVr\&.Instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 24 of file ObjectHiveVr\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
