.TH "ObjectHive" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectHive
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAim\fP \fBAim\fP"
.br
.ti -1c
.RI "\fBKeyboardInputController\fP \fBKeyboardInputController\fP"
.br
.ti -1c
.RI "\fBModelImportManager\fP \fBModelImportManager\fP"
.br
.ti -1c
.RI "UnityStandardAssets\&.Characters\&.FirstPerson\&.RigidbodyFirstPersonController \fBPlayerController\fP"
.br
.ti -1c
.RI "\fBIWheretyPlayer\fP \fBPlayer\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBObjectHive\fP \fBInstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file ObjectHive\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void ObjectHive\&.Awake ()"

.PP
Definition at line 25 of file ObjectHive\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAim\fP ObjectHive\&.Aim"

.PP
Definition at line 7 of file ObjectHive\&.cs\&.
.SS "\fBKeyboardInputController\fP ObjectHive\&.KeyboardInputController"

.PP
Definition at line 8 of file ObjectHive\&.cs\&.
.SS "\fBModelImportManager\fP ObjectHive\&.ModelImportManager"

.PP
Definition at line 9 of file ObjectHive\&.cs\&.
.SS "\fBIWheretyPlayer\fP ObjectHive\&.Player"

.PP
Definition at line 11 of file ObjectHive\&.cs\&.
.SS "UnityStandardAssets\&.Characters\&.FirstPerson\&.RigidbodyFirstPersonController ObjectHive\&.PlayerController"

.PP
Definition at line 10 of file ObjectHive\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBObjectHive\fP ObjectHive\&.Instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 16 of file ObjectHive\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
