.TH "PlantSettings" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlantSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBId\fP"
.br
.ti -1c
.RI "string \fBName\fP"
.br
.ti -1c
.RI "string \fBLocationDescription\fP"
.br
.ti -1c
.RI "string \fBCompany\fP"
.br
.ti -1c
.RI "string \fBDescription\fP"
.br
.ti -1c
.RI "float \fBLatitudeFullDeg\fP"
.br
.ti -1c
.RI "float \fBLongitudeFullDeg\fP"
.br
.ti -1c
.RI "List< string > \fBRvmFilesNames\fP"
.br
.ti -1c
.RI "List< string > \fBAttFilesNames\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file PlantSettings\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<string> PlantSettings\&.AttFilesNames"

.PP
Definition at line 16 of file PlantSettings\&.cs\&.
.SS "string PlantSettings\&.Company"

.PP
Definition at line 11 of file PlantSettings\&.cs\&.
.SS "string PlantSettings\&.Description"

.PP
Definition at line 12 of file PlantSettings\&.cs\&.
.SS "int PlantSettings\&.Id"

.PP
Definition at line 8 of file PlantSettings\&.cs\&.
.SS "float PlantSettings\&.LatitudeFullDeg"

.PP
Definition at line 13 of file PlantSettings\&.cs\&.
.SS "string PlantSettings\&.LocationDescription"

.PP
Definition at line 10 of file PlantSettings\&.cs\&.
.SS "float PlantSettings\&.LongitudeFullDeg"

.PP
Definition at line 14 of file PlantSettings\&.cs\&.
.SS "string PlantSettings\&.Name"

.PP
Definition at line 9 of file PlantSettings\&.cs\&.
.SS "List<string> PlantSettings\&.RvmFilesNames"

.PP
Definition at line 15 of file PlantSettings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
