.TH "PolygonData" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PolygonData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPolygonData\fP (Vector3[] vertices, Vector3[] normals)"
.br
.ti -1c
.RI "Vector2 [] \fBGetInPolygonsPlaneVerticesPresentation\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 [] \fBVertices\fP"
.br
.ti -1c
.RI "readonly Vector3 [] \fBNormals\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file PolygonData\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PolygonData\&.PolygonData (Vector3 [] vertices, Vector3 [] normals)"

.PP
Definition at line 8 of file PolygonData\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Vector2 [] PolygonData\&.GetInPolygonsPlaneVerticesPresentation ()"

.PP
Definition at line 14 of file PolygonData\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly Vector3 [] PolygonData\&.Normals"

.PP
Definition at line 6 of file PolygonData\&.cs\&.
.SS "Vector3 [] PolygonData\&.Vertices"

.PP
Definition at line 5 of file PolygonData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
