.TH "PrimitiveShapeData" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PrimitiveShapeData
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShapeData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrimitiveShapeData\fP (Matrix4x4 transformMatrix, Vector3 boundMin, Vector3 boundMax, float[] parameters, int parentId)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly float [] \fBParameters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file PrimitiveShapeData\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PrimitiveShapeData\&.PrimitiveShapeData (Matrix4x4 transformMatrix, Vector3 boundMin, Vector3 boundMax, float [] parameters, int parentId)"

.PP
Definition at line 7 of file PrimitiveShapeData\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly float [] PrimitiveShapeData\&.Parameters"

.PP
Definition at line 5 of file PrimitiveShapeData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
