.TH "ProgressData" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProgressData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBMessage\fP"
.br
.ti -1c
.RI "int \fBTotalToDoCount\fP"
.br
.ti -1c
.RI "int \fBCompletedCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file ProgressData\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int ProgressData\&.CompletedCount"

.PP
Definition at line 5 of file ProgressData\&.cs\&.
.SS "string ProgressData\&.Message"

.PP
Definition at line 3 of file ProgressData\&.cs\&.
.SS "int ProgressData\&.TotalToDoCount"

.PP
Definition at line 4 of file ProgressData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
