.TH "ProgressUi" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProgressUi
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and \fBIWindow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHide\fP ()"
.br
.ti -1c
.RI "void \fBShow\fP (object dataObject=null)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBProgressText\fP"
.br
.ti -1c
.RI "Slider \fBProgressSlider\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ProgressUi\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void ProgressUi\&.Hide ()"

.PP
Implements \fBIWindow\fP\&.
.PP
Definition at line 11 of file ProgressUi\&.cs\&.
.SS "void ProgressUi\&.Show (object dataObject = \fCnull\fP)"

.PP
Implements \fBIWindow\fP\&.
.PP
Definition at line 18 of file ProgressUi\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Slider ProgressUi\&.ProgressSlider"

.PP
Definition at line 9 of file ProgressUi\&.cs\&.
.SS "Text ProgressUi\&.ProgressText"

.PP
Definition at line 8 of file ProgressUi\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
