.TH "D:/Workspace/Unity/RVM_Importer/Assets/Scripts/RvmConverter.cs" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Workspace/Unity/RVM_Importer/Assets/Scripts/RvmConverter.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRvmConverter\fP"
.br
.RI "Основной класс \fBRvmConverter\fP, инициализируется в качестве компонента на пустом игровом объекте в сцене\&. Осуществляет управление процессами импорта модели и её инстанциировании в сцене\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
