.TH "RvmReader" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RvmReader
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShapeDataRepository\fP \fBRead\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBFileName\fP"
.br
.ti -1c
.RI "float \fBUnitsScale\fP = 0\&.001f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file RvmReader\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBShapeDataRepository\fP RvmReader\&.Read ()"

.PP
Definition at line 23 of file RvmReader\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string RvmReader\&.FileName"

.PP
Definition at line 9 of file RvmReader\&.cs\&.
.SS "float RvmReader\&.UnitsScale = 0\&.001f"

.PP
Definition at line 10 of file RvmReader\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
