.TH "RvmStructureReader" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RvmStructureReader
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBFileName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file RvmStructureReader\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string RvmStructureReader\&.FileName"

.PP
Definition at line 9 of file RvmStructureReader\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
