.TH "SceneShapesInstantiator" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneShapesInstantiator
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetShapeDataRepository\fP (\fBShapeDataRepository\fP dataRepository)"
.br
.ti -1c
.RI "void \fBCreateHierarchy\fP ()"
.br
.ti -1c
.RI "void \fBCreateAllShapes\fP ()"
.br
.ti -1c
.RI "void \fBSetModelRotationAndMirroring\fP ()"
.br
.ti -1c
.RI "void \fBCreateAllColliders\fP ()"
.br
.ti -1c
.RI "void \fBAssignColorsToAllShapes\fP ()"
.br
.ti -1c
.RI "void \fBCreateColliders\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBuilderSettings\fP \fBBuilderSettings\fP"
.br
.ti -1c
.RI "bool \fBOptimizeForStaticBatching\fP"
.br
.ti -1c
.RI "int \fBDuplicatesThresholdForSwitchingToInstancing\fP"
.br
.ti -1c
.RI "bool \fBTruncatedPyramids\fP"
.br
.ti -1c
.RI "bool \fBBoxes\fP"
.br
.ti -1c
.RI "bool \fBRectangularToroids\fP"
.br
.ti -1c
.RI "bool \fBToroids\fP"
.br
.ti -1c
.RI "bool \fBEllipticalDishes\fP"
.br
.ti -1c
.RI "bool \fBSphericalDishes\fP"
.br
.ti -1c
.RI "bool \fBSnouts\fP"
.br
.ti -1c
.RI "bool \fBCylinders\fP"
.br
.ti -1c
.RI "bool \fBSpheres\fP"
.br
.ti -1c
.RI "bool \fBCreateMultipleMeshes\fP"
.br
.ti -1c
.RI "bool \fBShearedCylinders\fP"
.br
.ti -1c
.RI "Transform \fBRootTransform\fP"
.br
.ti -1c
.RI "Material \fBStandardMaterial\fP"
.br
.ti -1c
.RI "Transform \fBCameraRig\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBShapeDataRepository\fP \fBShapeDataRepository\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file SceneShapesInstantiator\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void SceneShapesInstantiator\&.AssignColorsToAllShapes ()"

.PP
Definition at line 641 of file SceneShapesInstantiator\&.cs\&.
.SS "void SceneShapesInstantiator\&.CreateAllColliders ()"

.PP
Definition at line 201 of file SceneShapesInstantiator\&.cs\&.
.SS "void SceneShapesInstantiator\&.CreateAllShapes ()"

.PP
Definition at line 83 of file SceneShapesInstantiator\&.cs\&.
.SS "void SceneShapesInstantiator\&.CreateColliders ()"

.PP
Definition at line 759 of file SceneShapesInstantiator\&.cs\&.
.SS "void SceneShapesInstantiator\&.CreateHierarchy ()"

.PP
Definition at line 51 of file SceneShapesInstantiator\&.cs\&.
.SS "void SceneShapesInstantiator\&.SetModelRotationAndMirroring ()"

.PP
Definition at line 191 of file SceneShapesInstantiator\&.cs\&.
.SS "void SceneShapesInstantiator\&.SetShapeDataRepository (\fBShapeDataRepository\fP dataRepository)"

.PP
Definition at line 45 of file SceneShapesInstantiator\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool SceneShapesInstantiator\&.Boxes"

.PP
Definition at line 14 of file SceneShapesInstantiator\&.cs\&.
.SS "\fBBuilderSettings\fP SceneShapesInstantiator\&.BuilderSettings"

.PP
Definition at line 8 of file SceneShapesInstantiator\&.cs\&.
.SS "Transform SceneShapesInstantiator\&.CameraRig"

.PP
Definition at line 35 of file SceneShapesInstantiator\&.cs\&.
.SS "bool SceneShapesInstantiator\&.CreateMultipleMeshes"

.PP
Definition at line 22 of file SceneShapesInstantiator\&.cs\&.
.SS "bool SceneShapesInstantiator\&.Cylinders"

.PP
Definition at line 20 of file SceneShapesInstantiator\&.cs\&.
.SS "int SceneShapesInstantiator\&.DuplicatesThresholdForSwitchingToInstancing"

.PP
Definition at line 10 of file SceneShapesInstantiator\&.cs\&.
.SS "bool SceneShapesInstantiator\&.EllipticalDishes"

.PP
Definition at line 17 of file SceneShapesInstantiator\&.cs\&.
.SS "bool SceneShapesInstantiator\&.OptimizeForStaticBatching"

.PP
Definition at line 9 of file SceneShapesInstantiator\&.cs\&.
.SS "bool SceneShapesInstantiator\&.RectangularToroids"

.PP
Definition at line 15 of file SceneShapesInstantiator\&.cs\&.
.SS "Transform SceneShapesInstantiator\&.RootTransform"

.PP
Definition at line 32 of file SceneShapesInstantiator\&.cs\&.
.SS "bool SceneShapesInstantiator\&.ShearedCylinders"

.PP
Definition at line 23 of file SceneShapesInstantiator\&.cs\&.
.SS "bool SceneShapesInstantiator\&.Snouts"

.PP
Definition at line 19 of file SceneShapesInstantiator\&.cs\&.
.SS "bool SceneShapesInstantiator\&.Spheres"

.PP
Definition at line 21 of file SceneShapesInstantiator\&.cs\&.
.SS "bool SceneShapesInstantiator\&.SphericalDishes"

.PP
Definition at line 18 of file SceneShapesInstantiator\&.cs\&.
.SS "Material SceneShapesInstantiator\&.StandardMaterial"

.PP
Definition at line 34 of file SceneShapesInstantiator\&.cs\&.
.SS "bool SceneShapesInstantiator\&.Toroids"

.PP
Definition at line 16 of file SceneShapesInstantiator\&.cs\&.
.SS "bool SceneShapesInstantiator\&.TruncatedPyramids"

.PP
Definition at line 13 of file SceneShapesInstantiator\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBShapeDataRepository\fP SceneShapesInstantiator\&.ShapeDataRepository\fC [get]\fP"

.PP
Definition at line 43 of file SceneShapesInstantiator\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
