.TH "SelectAndShowAttributesMessage" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SelectAndShowAttributesMessage
.SH SYNOPSIS
.br
.PP
.PP
Inherits MessageBase\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBName\fP"
.br
.ti -1c
.RI "string \fBNickname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file SelectAndShowAttributesMessage\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string SelectAndShowAttributesMessage\&.Name"

.PP
Definition at line 5 of file SelectAndShowAttributesMessage\&.cs\&.
.SS "string SelectAndShowAttributesMessage\&.Nickname"

.PP
Definition at line 6 of file SelectAndShowAttributesMessage\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
