.TH "SettingsManager" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SettingsManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStorePlantSettings\fP (\fBPlantSettings\fP plant)"
.br
.ti -1c
.RI "void \fBErasePlantSettings\fP (int id)"
.br
.ti -1c
.RI "\fBPlantSettings\fP \fBGetPlantSettings\fP (int id)"
.br
.ti -1c
.RI "List< \fBPlantSettings\fP > \fBGetAllPlantsSettings\fP ()"
.br
.ti -1c
.RI "void \fBPopulateMockPlants\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file SettingsManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void SettingsManager\&.ErasePlantSettings (int id)"

.PP
Definition at line 93 of file SettingsManager\&.cs\&.
.SS "List<\fBPlantSettings\fP> SettingsManager\&.GetAllPlantsSettings ()"

.PP
Definition at line 158 of file SettingsManager\&.cs\&.
.SS "\fBPlantSettings\fP SettingsManager\&.GetPlantSettings (int id)"

.PP
Definition at line 115 of file SettingsManager\&.cs\&.
.SS "void SettingsManager\&.PopulateMockPlants ()"

.PP
Definition at line 182 of file SettingsManager\&.cs\&.
.SS "void SettingsManager\&.StorePlantSettings (\fBPlantSettings\fP plant)"

.PP
Definition at line 71 of file SettingsManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
