.TH "ShapeBaseData" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShapeBaseData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShapeBaseData\fP (float[] parameters)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly float [] \fBParameters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file ShapeBaseData\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ShapeBaseData\&.ShapeBaseData (float [] parameters)"

.PP
Definition at line 5 of file ShapeBaseData\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly float [] ShapeBaseData\&.Parameters"

.PP
Definition at line 3 of file ShapeBaseData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
