.TH "D:/Workspace/Unity/RVM_Importer/Assets/Scripts/ShapeTypes.cs" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Workspace/Unity/RVM_Importer/Assets/Scripts/ShapeTypes.cs
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBShapeTypes\fP { \fBShapeTypes\&.TruncatedPyramids\fP, \fBShapeTypes\&.Boxes\fP, \fBShapeTypes\&.RectangularToroids\fP, \fBShapeTypes\&.Toroids\fP, \fBShapeTypes\&.EllipticalDishes\fP, \fBShapeTypes\&.SphericalDishes\fP, \fBShapeTypes\&.Snouts\fP, \fBShapeTypes\&.Cylinders\fP, \fBShapeTypes\&.Spheres\fP, \fBShapeTypes\&.Lines\fP, \fBShapeTypes\&.MultipleMeshes\fP, \fBShapeTypes\&.ShearedCylinders\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBShapeTypes\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITruncatedPyramids \fP\fP
.TP
\fB\fIBoxes \fP\fP
.TP
\fB\fIRectangularToroids \fP\fP
.TP
\fB\fIToroids \fP\fP
.TP
\fB\fIEllipticalDishes \fP\fP
.TP
\fB\fISphericalDishes \fP\fP
.TP
\fB\fISnouts \fP\fP
.TP
\fB\fICylinders \fP\fP
.TP
\fB\fISpheres \fP\fP
.TP
\fB\fILines \fP\fP
.TP
\fB\fIMultipleMeshes \fP\fP
.TP
\fB\fIShearedCylinders \fP\fP
.PP
Definition at line 5 of file ShapeTypes\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
