.TH "ShapeData" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShapeData
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMultipleMeshShapeData\fP, and \fBPrimitiveShapeData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShapeData\fP (Matrix4x4 transformMatrix, Vector3 boundMin, Vector3 boundMax, int parentId)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly Matrix4x4 \fBTransformMatrix\fP"
.br
.ti -1c
.RI "readonly Vector3 \fBBoundMin\fP"
.br
.ti -1c
.RI "readonly Vector3 \fBBoundMax\fP"
.br
.ti -1c
.RI "Transform \fBTransform\fP"
.br
.ti -1c
.RI "readonly int \fBParentId\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file ShapeData\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ShapeData\&.ShapeData (Matrix4x4 transformMatrix, Vector3 boundMin, Vector3 boundMax, int parentId)"

.PP
Definition at line 12 of file ShapeData\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly Vector3 ShapeData\&.BoundMax"

.PP
Definition at line 7 of file ShapeData\&.cs\&.
.SS "readonly Vector3 ShapeData\&.BoundMin"

.PP
Definition at line 6 of file ShapeData\&.cs\&.
.SS "readonly int ShapeData\&.ParentId"

.PP
Definition at line 10 of file ShapeData\&.cs\&.
.SS "Transform ShapeData\&.Transform"

.PP
Definition at line 8 of file ShapeData\&.cs\&.
.SS "readonly Matrix4x4 ShapeData\&.TransformMatrix"

.PP
Definition at line 5 of file ShapeData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
