.TH "SmoothLathingLodSettings" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SmoothLathingLodSettings
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLodSettings\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSmoothLathingLodSettings\fP (float screenRelativeTransitionHeight, float revoluteStep, float circularStep)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly float \fBRevoluteStep\fP"
.br
.ti -1c
.RI "readonly float \fBCircularStep\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file SmoothLathingLodSettings\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SmoothLathingLodSettings\&.SmoothLathingLodSettings (float screenRelativeTransitionHeight, float revoluteStep, float circularStep)"

.PP
Definition at line 5 of file SmoothLathingLodSettings\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly float SmoothLathingLodSettings\&.CircularStep"

.PP
Definition at line 4 of file SmoothLathingLodSettings\&.cs\&.
.SS "readonly float SmoothLathingLodSettings\&.RevoluteStep"

.PP
Definition at line 3 of file SmoothLathingLodSettings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
