.TH "TelekineticHand" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TelekineticHand
.SH SYNOPSIS
.br
.PP
.PP
Inherits Hand\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.ti -1c
.RI "override void \fBUpdateHovering\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file TelekineticHand\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TelekineticHand\&.Awake ()\fC [protected]\fP"

.PP
Definition at line 9 of file TelekineticHand\&.cs\&.
.SS "override void TelekineticHand\&.UpdateHovering ()\fC [protected]\fP"

.PP
Definition at line 15 of file TelekineticHand\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
