.TH "Telekinesis" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Telekinesis
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SteamVR_Action_Single \fBTelekinesisAiming\fP"
.br
.ti -1c
.RI "SteamVR_Action_Boolean \fBTelekinesisAction\fP"
.br
.ti -1c
.RI "GameObject \fBTelekineticTracingLineGo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Telekinesis\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "SteamVR_Action_Boolean Telekinesis\&.TelekinesisAction"

.PP
Definition at line 8 of file Telekinesis\&.cs\&.
.SS "SteamVR_Action_Single Telekinesis\&.TelekinesisAiming"

.PP
Definition at line 7 of file Telekinesis\&.cs\&.
.SS "GameObject Telekinesis\&.TelekineticTracingLineGo"

.PP
Definition at line 10 of file Telekinesis\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
