.TH "TestSphericalLathingBuilder" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestSphericalLathingBuilder
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBH\fP = 10f"
.br
.ti -1c
.RI "float \fBS\fP = 30f"
.br
.ti -1c
.RI "float \fBFillAngle\fP = 360f"
.br
.ti -1c
.RI "float \fBRevoluteStep\fP = 15f"
.br
.ti -1c
.RI "float \fBCircularStep\fP = 15f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file TestSphericalLathingBuilder\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float TestSphericalLathingBuilder\&.CircularStep = 15f"

.PP
Definition at line 11 of file TestSphericalLathingBuilder\&.cs\&.
.SS "float TestSphericalLathingBuilder\&.FillAngle = 360f"

.PP
Definition at line 8 of file TestSphericalLathingBuilder\&.cs\&.
.SS "float TestSphericalLathingBuilder\&.H = 10f"

.PP
Definition at line 6 of file TestSphericalLathingBuilder\&.cs\&.
.SS "float TestSphericalLathingBuilder\&.RevoluteStep = 15f"

.PP
Definition at line 10 of file TestSphericalLathingBuilder\&.cs\&.
.SS "float TestSphericalLathingBuilder\&.S = 30f"

.PP
Definition at line 7 of file TestSphericalLathingBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
