.TH "TestTruncatedShiftedConeBuilder" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestTruncatedShiftedConeBuilder
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBBottomRadius\fP = 22\&.5f"
.br
.ti -1c
.RI "float \fBTopRadius\fP = 16\&.5f"
.br
.ti -1c
.RI "float \fBHeight\fP = 20f"
.br
.ti -1c
.RI "float \fBOffsetX\fP = 5f"
.br
.ti -1c
.RI "float \fBOffsetY\fP = 10f"
.br
.ti -1c
.RI "float \fBCircularStep\fP = 15f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file TestTruncatedShiftedConeBuilder\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float TestTruncatedShiftedConeBuilder\&.BottomRadius = 22\&.5f"

.PP
Definition at line 6 of file TestTruncatedShiftedConeBuilder\&.cs\&.
.SS "float TestTruncatedShiftedConeBuilder\&.CircularStep = 15f"

.PP
Definition at line 12 of file TestTruncatedShiftedConeBuilder\&.cs\&.
.SS "float TestTruncatedShiftedConeBuilder\&.Height = 20f"

.PP
Definition at line 8 of file TestTruncatedShiftedConeBuilder\&.cs\&.
.SS "float TestTruncatedShiftedConeBuilder\&.OffsetX = 5f"

.PP
Definition at line 9 of file TestTruncatedShiftedConeBuilder\&.cs\&.
.SS "float TestTruncatedShiftedConeBuilder\&.OffsetY = 10f"

.PP
Definition at line 10 of file TestTruncatedShiftedConeBuilder\&.cs\&.
.SS "float TestTruncatedShiftedConeBuilder\&.TopRadius = 16\&.5f"

.PP
Definition at line 7 of file TestTruncatedShiftedConeBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
