.TH "TestSphereBuilder" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestSphereBuilder
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBR\fP = 50f"
.br
.ti -1c
.RI "float \fBFillAngle\fP = 2 * Mathf\&.PI"
.br
.ti -1c
.RI "float \fBRevoluteStep\fP = 15f"
.br
.ti -1c
.RI "float \fBCircularStep\fP = 15f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file TestSphereBuilder\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float TestSphereBuilder\&.CircularStep = 15f"

.PP
Definition at line 12 of file TestSphereBuilder\&.cs\&.
.SS "float TestSphereBuilder\&.FillAngle = 2 * Mathf\&.PI"

.PP
Definition at line 9 of file TestSphereBuilder\&.cs\&.
.SS "float TestSphereBuilder\&.R = 50f"

.PP
Definition at line 8 of file TestSphereBuilder\&.cs\&.
.SS "float TestSphereBuilder\&.RevoluteStep = 15f"

.PP
Definition at line 11 of file TestSphereBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
