.TH "TestToroidBuilder" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestToroidBuilder
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBRevoluteRadius\fP = 50f"
.br
.ti -1c
.RI "float \fBCircularRadius\fP = 10f"
.br
.ti -1c
.RI "float \fBFillAngle\fP = 3\&.1415927f"
.br
.ti -1c
.RI "float \fBRevoluteStep\fP = 60f"
.br
.ti -1c
.RI "float \fBCircularStep\fP = 60f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file TestToroidBuilder\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float TestToroidBuilder\&.CircularRadius = 10f"

.PP
Definition at line 7 of file TestToroidBuilder\&.cs\&.
.SS "float TestToroidBuilder\&.CircularStep = 60f"

.PP
Definition at line 11 of file TestToroidBuilder\&.cs\&.
.SS "float TestToroidBuilder\&.FillAngle = 3\&.1415927f"

.PP
Definition at line 8 of file TestToroidBuilder\&.cs\&.
.SS "float TestToroidBuilder\&.RevoluteRadius = 50f"

.PP
Definition at line 6 of file TestToroidBuilder\&.cs\&.
.SS "float TestToroidBuilder\&.RevoluteStep = 60f"

.PP
Definition at line 10 of file TestToroidBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
