.TH "TestCylinderBuilder" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestCylinderBuilder
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBRadius\fP = 50f"
.br
.ti -1c
.RI "float \fBHeight\fP = 10f"
.br
.ti -1c
.RI "bool \fBBuildCaps\fP = true"
.br
.ti -1c
.RI "float \fBCircularStep\fP = 15f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file TestCylinderBuilder\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool TestCylinderBuilder\&.BuildCaps = true"

.PP
Definition at line 9 of file TestCylinderBuilder\&.cs\&.
.SS "float TestCylinderBuilder\&.CircularStep = 15f"

.PP
Definition at line 11 of file TestCylinderBuilder\&.cs\&.
.SS "float TestCylinderBuilder\&.Height = 10f"

.PP
Definition at line 7 of file TestCylinderBuilder\&.cs\&.
.SS "float TestCylinderBuilder\&.Radius = 50f"

.PP
Definition at line 6 of file TestCylinderBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
