.TH "TestEllipticalLathingBuilder" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestEllipticalLathingBuilder
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBA\fP = 50f"
.br
.ti -1c
.RI "float \fBB\fP = 10f"
.br
.ti -1c
.RI "float \fBFillAngle\fP = 360f"
.br
.ti -1c
.RI "float \fBRevoluteStep\fP = 15f"
.br
.ti -1c
.RI "float \fBCircularStep\fP = 15f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file TestEllipticalLathingBuilder\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float TestEllipticalLathingBuilder\&.A = 50f"

.PP
Definition at line 6 of file TestEllipticalLathingBuilder\&.cs\&.
.SS "float TestEllipticalLathingBuilder\&.B = 10f"

.PP
Definition at line 7 of file TestEllipticalLathingBuilder\&.cs\&.
.SS "float TestEllipticalLathingBuilder\&.CircularStep = 15f"

.PP
Definition at line 11 of file TestEllipticalLathingBuilder\&.cs\&.
.SS "float TestEllipticalLathingBuilder\&.FillAngle = 360f"

.PP
Definition at line 8 of file TestEllipticalLathingBuilder\&.cs\&.
.SS "float TestEllipticalLathingBuilder\&.RevoluteStep = 15f"

.PP
Definition at line 10 of file TestEllipticalLathingBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
