.TH "TestSlopedCylinderBuilder" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestSlopedCylinderBuilder
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBRadius\fP = 22\&.5f"
.br
.ti -1c
.RI "float \fBHeight\fP = 20f"
.br
.ti -1c
.RI "float \fBBottomAngleX\fP = 0f"
.br
.ti -1c
.RI "float \fBBottomAngleY\fP = 0f"
.br
.ti -1c
.RI "float \fBTopAngleX\fP = 0f"
.br
.ti -1c
.RI "float \fBTopAngleY\fP = 0\&.0003490659f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file TestSlopedCylinderBuilder\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float TestSlopedCylinderBuilder\&.BottomAngleX = 0f"

.PP
Definition at line 8 of file TestSlopedCylinderBuilder\&.cs\&.
.SS "float TestSlopedCylinderBuilder\&.BottomAngleY = 0f"

.PP
Definition at line 9 of file TestSlopedCylinderBuilder\&.cs\&.
.SS "float TestSlopedCylinderBuilder\&.Height = 20f"

.PP
Definition at line 7 of file TestSlopedCylinderBuilder\&.cs\&.
.SS "float TestSlopedCylinderBuilder\&.Radius = 22\&.5f"

.PP
Definition at line 6 of file TestSlopedCylinderBuilder\&.cs\&.
.SS "float TestSlopedCylinderBuilder\&.TopAngleX = 0f"

.PP
Definition at line 10 of file TestSlopedCylinderBuilder\&.cs\&.
.SS "float TestSlopedCylinderBuilder\&.TopAngleY = 0\&.0003490659f"

.PP
Definition at line 11 of file TestSlopedCylinderBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
