.TH "TriangleVertices" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TriangleVertices
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBStartingNumber\fP"
.br
.ti -1c
.RI "int \fBCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 403 of file XPlaneImporter\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int TriangleVertices\&.Count"

.PP
Definition at line 406 of file XPlaneImporter\&.cs\&.
.SS "int TriangleVertices\&.StartingNumber"

.PP
Definition at line 405 of file XPlaneImporter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
