.TH "UiManagerVr" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UiManagerVr
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShowModelImportUi\fP ()"
.br
.ti -1c
.RI "void \fBShowActionMenuUi\fP (\fBInteractionObject\fP interactionObject)"
.br
.ti -1c
.RI "void \fBShowProgressUi\fP (\fBProgressData\fP data)"
.br
.ti -1c
.RI "void \fBHideCurrentWindow\fP ()"
.br
.ti -1c
.RI "void \fBUpdateWindow\fP (\fBIWindow\fP window, object dataObject=null)"
.br
.ti -1c
.RI "void \fBHideObject\fP (string objectName)"
.br
.ti -1c
.RI "void \fBInteractWithObject\fP (string objectName)"
.br
.ti -1c
.RI "void \fBShowInfoPad\fP (string title, string left, string center, string right)"
.br
.ti -1c
.RI "void \fBHideInfoPad\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBModelImportUiVr\fP \fBModelImportUi\fP"
.br
.ti -1c
.RI "\fBActionMenuUi\fP \fBActionMenuUi\fP"
.br
.ti -1c
.RI "\fBProgressUi\fP \fBProgressUi\fP"
.br
.ti -1c
.RI "GameObject \fBShowModelImportUiButton\fP"
.br
.ti -1c
.RI "GameObject \fBInfoPadGo\fP"
.br
.ti -1c
.RI "Text \fBInfoPadTitleText\fP"
.br
.ti -1c
.RI "Text \fBInfoPadTextLeft\fP"
.br
.ti -1c
.RI "Text \fBInfoPadTextCenter\fP"
.br
.ti -1c
.RI "Text \fBInfoPadTextRight\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBUiManagerVr\fP \fBI\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file UiManagerVr\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UiManagerVr\&.HideCurrentWindow ()"

.PP
Definition at line 48 of file UiManagerVr\&.cs\&.
.SS "void UiManagerVr\&.HideInfoPad ()"

.PP
Definition at line 95 of file UiManagerVr\&.cs\&.
.SS "void UiManagerVr\&.HideObject (string objectName)"

.PP
Definition at line 70 of file UiManagerVr\&.cs\&.
.SS "void UiManagerVr\&.InteractWithObject (string objectName)"

.PP
Definition at line 77 of file UiManagerVr\&.cs\&.
.SS "void UiManagerVr\&.ShowActionMenuUi (\fBInteractionObject\fP interactionObject)"

.PP
Definition at line 38 of file UiManagerVr\&.cs\&.
.SS "void UiManagerVr\&.ShowInfoPad (string title, string left, string center, string right)"

.PP
Definition at line 86 of file UiManagerVr\&.cs\&.
.SS "void UiManagerVr\&.ShowModelImportUi ()"

.PP
Definition at line 33 of file UiManagerVr\&.cs\&.
.SS "void UiManagerVr\&.ShowProgressUi (\fBProgressData\fP data)"

.PP
Definition at line 43 of file UiManagerVr\&.cs\&.
.SS "void UiManagerVr\&.UpdateWindow (\fBIWindow\fP window, object dataObject = \fCnull\fP)"

.PP
Definition at line 63 of file UiManagerVr\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBActionMenuUi\fP UiManagerVr\&.ActionMenuUi"

.PP
Definition at line 12 of file UiManagerVr\&.cs\&.
.SS "GameObject UiManagerVr\&.InfoPadGo"

.PP
Definition at line 17 of file UiManagerVr\&.cs\&.
.SS "Text UiManagerVr\&.InfoPadTextCenter"

.PP
Definition at line 20 of file UiManagerVr\&.cs\&.
.SS "Text UiManagerVr\&.InfoPadTextLeft"

.PP
Definition at line 19 of file UiManagerVr\&.cs\&.
.SS "Text UiManagerVr\&.InfoPadTextRight"

.PP
Definition at line 21 of file UiManagerVr\&.cs\&.
.SS "Text UiManagerVr\&.InfoPadTitleText"

.PP
Definition at line 18 of file UiManagerVr\&.cs\&.
.SS "\fBModelImportUiVr\fP UiManagerVr\&.ModelImportUi"

.PP
Definition at line 11 of file UiManagerVr\&.cs\&.
.SS "\fBProgressUi\fP UiManagerVr\&.ProgressUi"

.PP
Definition at line 13 of file UiManagerVr\&.cs\&.
.SS "GameObject UiManagerVr\&.ShowModelImportUiButton"

.PP
Definition at line 15 of file UiManagerVr\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBUiManagerVr\fP UiManagerVr\&.I\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 24 of file UiManagerVr\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
