.TH "UiManager" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UiManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShowModelImportUi\fP ()"
.br
.ti -1c
.RI "void \fBShowActionMenuUi\fP (\fBInteractionObject\fP interactionObject)"
.br
.ti -1c
.RI "void \fBShowProgressUi\fP (\fBProgressData\fP data)"
.br
.ti -1c
.RI "void \fBHideCurrentWindow\fP ()"
.br
.ti -1c
.RI "void \fBUpdateWindow\fP (\fBIWindow\fP window, object dataObject=null)"
.br
.ti -1c
.RI "void \fBHideObject\fP (string objectName)"
.br
.ti -1c
.RI "void \fBInteractWithObject\fP (string objectName)"
.br
.ti -1c
.RI "void \fBShowInfoPanel\fP (string message)"
.br
.ti -1c
.RI "void \fBHideInfoPanel\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBInformationPanel\fP"
.br
.ti -1c
.RI "\fBModelImportUi\fP \fBModelImportUi\fP"
.br
.ti -1c
.RI "\fBActionMenuUi\fP \fBActionMenuUi\fP"
.br
.ti -1c
.RI "\fBProgressUi\fP \fBProgressUi\fP"
.br
.ti -1c
.RI "GameObject \fBShowModelImportUiButton\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBUiManager\fP \fBI\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file UiManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UiManager\&.HideCurrentWindow ()"

.PP
Definition at line 43 of file UiManager\&.cs\&.
.SS "void UiManager\&.HideInfoPanel ()"

.PP
Definition at line 98 of file UiManager\&.cs\&.
.SS "void UiManager\&.HideObject (string objectName)"

.PP
Definition at line 76 of file UiManager\&.cs\&.
.SS "void UiManager\&.InteractWithObject (string objectName)"

.PP
Definition at line 83 of file UiManager\&.cs\&.
.SS "void UiManager\&.ShowActionMenuUi (\fBInteractionObject\fP interactionObject)"

.PP
Definition at line 33 of file UiManager\&.cs\&.
.SS "void UiManager\&.ShowInfoPanel (string message)"

.PP
Definition at line 92 of file UiManager\&.cs\&.
.SS "void UiManager\&.ShowModelImportUi ()"

.PP
Definition at line 28 of file UiManager\&.cs\&.
.SS "void UiManager\&.ShowProgressUi (\fBProgressData\fP data)"

.PP
Definition at line 38 of file UiManager\&.cs\&.
.SS "void UiManager\&.UpdateWindow (\fBIWindow\fP window, object dataObject = \fCnull\fP)"

.PP
Definition at line 63 of file UiManager\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBActionMenuUi\fP UiManager\&.ActionMenuUi"

.PP
Definition at line 13 of file UiManager\&.cs\&.
.SS "GameObject UiManager\&.InformationPanel"

.PP
Definition at line 7 of file UiManager\&.cs\&.
.SS "\fBModelImportUi\fP UiManager\&.ModelImportUi"

.PP
Definition at line 12 of file UiManager\&.cs\&.
.SS "\fBProgressUi\fP UiManager\&.ProgressUi"

.PP
Definition at line 14 of file UiManager\&.cs\&.
.SS "GameObject UiManager\&.ShowModelImportUiButton"

.PP
Definition at line 16 of file UiManager\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBUiManager\fP UiManager\&.I\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 19 of file UiManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
