.TH "VrMpPlayer" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VrMpPlayer
.SH SYNOPSIS
.br
.PP
.PP
Inherits NetworkBehaviour, and \fBIWheretyPlayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBHideObject\fP (string objectName)"
.br
.ti -1c
.RI "void \fBInteractWithObject\fP (string objectName)"
.br
.ti -1c
.RI "void \fBMoveObject\fP (Transform transform)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file VrMpPlayer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void VrMpPlayer\&.HideObject (string objectName)"

.PP
Implements \fBIWheretyPlayer\fP\&.
.PP
Definition at line 32 of file VrMpPlayer\&.cs\&.
.SS "void VrMpPlayer\&.InteractWithObject (string objectName)"

.PP
Implements \fBIWheretyPlayer\fP\&.
.PP
Definition at line 43 of file VrMpPlayer\&.cs\&.
.SS "void VrMpPlayer\&.MoveObject (Transform transform)"

.PP
Implements \fBIWheretyPlayer\fP\&.
.PP
Definition at line 54 of file VrMpPlayer\&.cs\&.
.SS "void VrMpPlayer\&.Start ()"

.PP
Definition at line 9 of file VrMpPlayer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
