.TH "WheretyPlayer" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WheretyPlayer
.SH SYNOPSIS
.br
.PP
.PP
Inherits NetworkBehaviour, and \fBIWheretyPlayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBShowWarning\fP ()"
.br
.ti -1c
.RI "void \fBHideObject\fP (string objectName)"
.br
.ti -1c
.RI "void \fBInteractWithObject\fP (string objectName)"
.br
.ti -1c
.RI "void \fBMoveObject\fP (Transform target)"
.br
.ti -1c
.RI "void \fBPlayPickupAnimation\fP ()"
.br
.ti -1c
.RI "void \fBSelectAndShowAttributes\fP (string name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBNickname\fP = 'User'"
.br
.ti -1c
.RI "GameObject \fBPlayerAvatarModel\fP"
.br
.ti -1c
.RI "Animator \fBAnimator\fP"
.br
.ti -1c
.RI "Text \fBNicknameText\fP"
.br
.ti -1c
.RI "GameObject \fBWarningTextCanvas\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file WheretyPlayer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void WheretyPlayer\&.HideObject (string objectName)"

.PP
Implements \fBIWheretyPlayer\fP\&.
.PP
Definition at line 111 of file WheretyPlayer\&.cs\&.
.SS "void WheretyPlayer\&.InteractWithObject (string objectName)"

.PP
Implements \fBIWheretyPlayer\fP\&.
.PP
Definition at line 122 of file WheretyPlayer\&.cs\&.
.SS "void WheretyPlayer\&.MoveObject (Transform target)"

.PP
Implements \fBIWheretyPlayer\fP\&.
.PP
Definition at line 133 of file WheretyPlayer\&.cs\&.
.SS "void WheretyPlayer\&.PlayPickupAnimation ()"

.PP
Definition at line 150 of file WheretyPlayer\&.cs\&.
.SS "void WheretyPlayer\&.SelectAndShowAttributes (string name)"

.PP
Definition at line 164 of file WheretyPlayer\&.cs\&.
.SS "void WheretyPlayer\&.ShowWarning ()"

.PP
Definition at line 67 of file WheretyPlayer\&.cs\&.
.SS "void WheretyPlayer\&.Start ()"

.PP
Definition at line 23 of file WheretyPlayer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Animator WheretyPlayer\&.Animator"

.PP
Definition at line 14 of file WheretyPlayer\&.cs\&.
.SS "string WheretyPlayer\&.Nickname = 'User'"

.PP
Definition at line 11 of file WheretyPlayer\&.cs\&.
.SS "Text WheretyPlayer\&.NicknameText"

.PP
Definition at line 15 of file WheretyPlayer\&.cs\&.
.SS "GameObject WheretyPlayer\&.PlayerAvatarModel"

.PP
Definition at line 13 of file WheretyPlayer\&.cs\&.
.SS "GameObject WheretyPlayer\&.WarningTextCanvas"

.PP
Definition at line 16 of file WheretyPlayer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
