.TH "WheretyNetworkManager" 3 "Thu May 16 2019" "CAD-BIM_Unity_Importer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WheretyNetworkManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits NetworkManager\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnClientConnect\fP (NetworkConnection connection)"
.br
.ti -1c
.RI "void \fBReceiveHideObjectMessage\fP (NetworkMessage networkMessage)"
.br
.ti -1c
.RI "void \fBReceiveInteractWithObjectMessage\fP (NetworkMessage networkMessage)"
.br
.ti -1c
.RI "void \fBReceiveMoveObjectMessage\fP (NetworkMessage networkMessage)"
.br
.ti -1c
.RI "void \fBReceivePlayPickupAnimationMessage\fP (NetworkMessage networkMessage)"
.br
.ti -1c
.RI "void \fBReceiveSelectAndShowAttributesMessage\fP (NetworkMessage networkMessage)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const short \fBHideObjectMessageType\fP = MsgType\&.Highest + 1"
.br
.ti -1c
.RI "const short \fBInteractWithObjectMessageType\fP = MsgType\&.Highest + 2"
.br
.ti -1c
.RI "const short \fBMoveObjectMessageType\fP = MsgType\&.Highest + 3"
.br
.ti -1c
.RI "const short \fBPlayPickupAnimationMessageType\fP = MsgType\&.Highest + 4"
.br
.ti -1c
.RI "const short \fBSelectAndShowAttributesMessageType\fP = MsgType\&.Highest + 5"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file WheretyNetworkManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void WheretyNetworkManager\&.OnClientConnect (NetworkConnection connection)"

.PP
Definition at line 14 of file WheretyNetworkManager\&.cs\&.
.SS "void WheretyNetworkManager\&.ReceiveHideObjectMessage (NetworkMessage networkMessage)"

.PP
Definition at line 25 of file WheretyNetworkManager\&.cs\&.
.SS "void WheretyNetworkManager\&.ReceiveInteractWithObjectMessage (NetworkMessage networkMessage)"

.PP
Definition at line 31 of file WheretyNetworkManager\&.cs\&.
.SS "void WheretyNetworkManager\&.ReceiveMoveObjectMessage (NetworkMessage networkMessage)"

.PP
Definition at line 37 of file WheretyNetworkManager\&.cs\&.
.SS "void WheretyNetworkManager\&.ReceivePlayPickupAnimationMessage (NetworkMessage networkMessage)"

.PP
Definition at line 49 of file WheretyNetworkManager\&.cs\&.
.SS "void WheretyNetworkManager\&.ReceiveSelectAndShowAttributesMessage (NetworkMessage networkMessage)"

.PP
Definition at line 63 of file WheretyNetworkManager\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const short WheretyNetworkManager\&.HideObjectMessageType = MsgType\&.Highest + 1"

.PP
Definition at line 8 of file WheretyNetworkManager\&.cs\&.
.SS "const short WheretyNetworkManager\&.InteractWithObjectMessageType = MsgType\&.Highest + 2"

.PP
Definition at line 9 of file WheretyNetworkManager\&.cs\&.
.SS "const short WheretyNetworkManager\&.MoveObjectMessageType = MsgType\&.Highest + 3"

.PP
Definition at line 10 of file WheretyNetworkManager\&.cs\&.
.SS "const short WheretyNetworkManager\&.PlayPickupAnimationMessageType = MsgType\&.Highest + 4"

.PP
Definition at line 11 of file WheretyNetworkManager\&.cs\&.
.SS "const short WheretyNetworkManager\&.SelectAndShowAttributesMessageType = MsgType\&.Highest + 5"

.PP
Definition at line 12 of file WheretyNetworkManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD-BIM_Unity_Importer from the source code\&.
